#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HangarDoor

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "S_JigPayload_structs.hpp"
#include "S_RandomStatsConfig_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_HangarDoor.BP_HangarDoor_C.BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature
// 0x000C (0x000C - 0x0000)
struct BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature final
{
public:
	bool                                          bIsBeyondLastLayer;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LayerIndex;                                        // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSeen;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x000004, "Wrong alignment on BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(sizeof(BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x00000C, "Wrong size on BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(offsetof(BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsBeyondLastLayer) == 0x000000, "Member 'BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, LayerIndex) == 0x000004, "Member 'BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::LayerIndex' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsSeen) == 0x000008, "Member 'BP_HangarDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsSeen' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.Event_OpenDoor
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_Event_OpenDoor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_Event_OpenDoor) == 0x000008, "Wrong alignment on BP_HangarDoor_C_Event_OpenDoor");
static_assert(sizeof(BP_HangarDoor_C_Event_OpenDoor) == 0x000008, "Wrong size on BP_HangarDoor_C_Event_OpenDoor");
static_assert(offsetof(BP_HangarDoor_C_Event_OpenDoor, Actor) == 0x000000, "Member 'BP_HangarDoor_C_Event_OpenDoor::Actor' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.ExecuteUbergraph_BP_HangarDoor
// 0x0558 (0x0558 - 0x0000)
struct BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_Event_Option_2;                             // 0x0004(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Lerp_ReturnValue;                         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<class FName, class FText>                K2Node_MakeMap_Map;                                // 0x0030(0x0050)()
	TMap<class FName, class FText>                K2Node_MakeMap_Map_1;                              // 0x0080(0x0050)()
	TMap<struct FGameplayTag, class FText>        K2Node_MakeMap_Map_2;                              // 0x00D0(0x0050)(ConstParm)
	bool                                          CallFunc_GetBoolCVar_ReturnValue;                  // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AHUD_Game_C*                            CallFunc_GetHUD_HUD;                               // 0x0128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AHUD_Game_C*                            CallFunc_GetHUD_HUD_1;                             // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_Actor_1;                        // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetBehindObject__BehindObject_;           // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_142[0x2];                                      // 0x0142(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           K2Node_Event_Option_1;                             // 0x0144(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_ByActor;                              // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FS_JigPayload                          K2Node_Event_Payload;                              // 0x0158(0x0030)(HasGetValueTypeHash)
	double                                        CallFunc_Lerp_ReturnValue_1;                       // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetDistanceTo_ReturnValue;                // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_194[0x4];                                      // 0x0194(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0198(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B3[0x5];                                      // 0x01B3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_InteractingActor_2;                   // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_Event_Option;                               // 0x01C0(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_InteractingActor_1;                   // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMap<struct FGameplayTag, class FText>        K2Node_Event_Options;                              // 0x01D0(0x0050)(ConstParm)
	TScriptInterface<class IBP_MpInteractInterface_C> K2Node_DynamicCast_AsBP_Mp_Interact_Interface; // 0x0220(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_OnRequestServerInteract_Result;           // 0x0231(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_232[0x6];                                      // 0x0232(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0238(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0250(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_1;  // 0x0338(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AActor*                                 K2Node_Event_InteractingActor_3;                   // 0x0420(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_InteractingActor;                     // 0x0428(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0430(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetAchievement_ReturnValue;               // 0x0448(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_StoreStats_ReturnValue;                   // 0x0449(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44A[0x6];                                      // 0x044A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_CustomEvent_Actor;                          // 0x0450(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_Player_C>         K2Node_DynamicCast_AsBPI_Player;                   // 0x0458(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0468(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469[0x7];                                      // 0x0469(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_JigMultiplayer_C*                   CallFunc_GetComponentByClass_ReturnValue;          // 0x0470(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0478(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_FindJigItemByDA_Result;                   // 0x0479(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47A[0x6];                                      // 0x047A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UJSI_Slot_C*                            CallFunc_FindJigItemByDA_Found;                    // 0x0480(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ServerFindThenConsumeByItemID_Result;     // 0x0488(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_489[0x7];                                      // 0x0489(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ULevellingComponent_C*                  CallFunc_GetLevellingComponent_LevellingComponent; // 0x0490(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_IntFloat_ReturnValue;            // 0x0498(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_AddXP_XPOutput;                           // 0x04A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x04A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4AC[0x4];                                      // 0x04AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x04B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x04B8(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0508(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0518(0x0018)()
	bool                                          K2Node_ComponentBoundEvent_bIsBeyondLastLayer;     // 0x0530(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_531[0x3];                                      // 0x0531(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_ComponentBoundEvent_LayerIndex;             // 0x0534(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsSeen;                // 0x0538(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_539[0x7];                                      // 0x0539(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Lerp_Alpha_ImplicitCast;                  // 0x0540(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_Alpha_ImplicitCast_1;                // 0x0548(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x0550(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor) == 0x000008, "Wrong alignment on BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor");
static_assert(sizeof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor) == 0x000558, "Wrong size on BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, EntryPoint) == 0x000000, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_Option_2) == 0x000004, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_Option_2' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_SwitchEnum_CmpSuccess) == 0x00000C, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Lerp_ReturnValue) == 0x000010, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Lerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_MakeVector_ReturnValue) == 0x000018, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_MakeMap_Map) == 0x000030, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_MakeMap_Map' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_MakeMap_Map_1) == 0x000080, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_MakeMap_Map_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_MakeMap_Map_2) == 0x0000D0, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_MakeMap_Map_2' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_GetBoolCVar_ReturnValue) == 0x000120, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_GetBoolCVar_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_GetHUD_HUD) == 0x000128, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_GetHUD_HUD' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_GetHUD_HUD_1) == 0x000130, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_GetHUD_HUD_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_CustomEvent_Actor_1) == 0x000138, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_CustomEvent_Actor_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_GetBehindObject__BehindObject_) == 0x000140, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_GetBehindObject__BehindObject_' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_HasAuthority_ReturnValue) == 0x000141, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_Option_1) == 0x000144, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_Option_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_ByActor) == 0x000150, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_ByActor' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_Payload) == 0x000158, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_Payload' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Lerp_ReturnValue_1) == 0x000188, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Lerp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_GetDistanceTo_ReturnValue) == 0x000190, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_GetDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_MakeVector_ReturnValue_1) == 0x000198, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Less_DoubleDouble_ReturnValue) == 0x0001B0, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_IsValid_ReturnValue) == 0x0001B1, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_BooleanAND_ReturnValue) == 0x0001B2, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_InteractingActor_2) == 0x0001B8, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_InteractingActor_2' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_Option) == 0x0001C0, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_Option' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_InteractingActor_1) == 0x0001C8, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_InteractingActor_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_Options) == 0x0001D0, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_Options' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_DynamicCast_AsBP_Mp_Interact_Interface) == 0x000220, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_DynamicCast_AsBP_Mp_Interact_Interface' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_DynamicCast_bSuccess) == 0x000230, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_OnRequestServerInteract_Result) == 0x000231, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_OnRequestServerInteract_Result' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000238, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000250, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_K2_SetRelativeLocation_SweepHitResult_1) == 0x000338, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_K2_SetRelativeLocation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_InteractingActor_3) == 0x000420, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_InteractingActor_3' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_Event_InteractingActor) == 0x000428, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_Event_InteractingActor' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000430, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_SetAchievement_ReturnValue) == 0x000448, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_SetAchievement_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_StoreStats_ReturnValue) == 0x000449, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_StoreStats_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_CustomEvent_Actor) == 0x000450, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_CustomEvent_Actor' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_DynamicCast_AsBPI_Player) == 0x000458, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_DynamicCast_AsBPI_Player' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_DynamicCast_bSuccess_1) == 0x000468, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_GetComponentByClass_ReturnValue) == 0x000470, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_IsValid_ReturnValue_1) == 0x000478, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_FindJigItemByDA_Result) == 0x000479, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_FindJigItemByDA_Result' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_FindJigItemByDA_Found) == 0x000480, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_FindJigItemByDA_Found' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_ServerFindThenConsumeByItemID_Result) == 0x000488, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_ServerFindThenConsumeByItemID_Result' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_GetLevellingComponent_LevellingComponent) == 0x000490, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_GetLevellingComponent_LevellingComponent' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Multiply_IntFloat_ReturnValue) == 0x000498, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Multiply_IntFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_AddXP_XPOutput) == 0x0004A0, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_AddXP_XPOutput' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_FTrunc_ReturnValue) == 0x0004A8, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Conv_IntToInt64_ReturnValue) == 0x0004B0, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_MakeStruct_FormatArgumentData) == 0x0004B8, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_MakeArray_Array) == 0x000508, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Format_ReturnValue) == 0x000518, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_ComponentBoundEvent_bIsBeyondLastLayer) == 0x000530, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_ComponentBoundEvent_bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_ComponentBoundEvent_LayerIndex) == 0x000534, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_ComponentBoundEvent_LayerIndex' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, K2Node_ComponentBoundEvent_bIsSeen) == 0x000538, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::K2Node_ComponentBoundEvent_bIsSeen' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Lerp_Alpha_ImplicitCast) == 0x000540, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Lerp_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Lerp_Alpha_ImplicitCast_1) == 0x000548, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Lerp_Alpha_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x000550, "Member 'BP_HangarDoor_C_ExecuteUbergraph_BP_HangarDoor::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.GetInteractOptions
// 0x00A0 (0x00A0 - 0x0000)
struct BP_HangarDoor_C_GetInteractOptions final
{
public:
	TMap<struct FGameplayTag, class FText>        Options;                                           // 0x0000(0x0050)(Parm, OutParm)
	TMap<struct FGameplayTag, class FText>        K2Node_MakeMap_Map;                                // 0x0050(0x0050)()
};
static_assert(alignof(BP_HangarDoor_C_GetInteractOptions) == 0x000008, "Wrong alignment on BP_HangarDoor_C_GetInteractOptions");
static_assert(sizeof(BP_HangarDoor_C_GetInteractOptions) == 0x0000A0, "Wrong size on BP_HangarDoor_C_GetInteractOptions");
static_assert(offsetof(BP_HangarDoor_C_GetInteractOptions, Options) == 0x000000, "Member 'BP_HangarDoor_C_GetInteractOptions::Options' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_GetInteractOptions, K2Node_MakeMap_Map) == 0x000050, "Member 'BP_HangarDoor_C_GetInteractOptions::K2Node_MakeMap_Map' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.GetItemInfo
// 0x0078 (0x0078 - 0x0000)
struct BP_HangarDoor_C_GetItemInfo final
{
public:
	class UJigsawItem_DataAsset_C*                Info;                                              // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Count;                                             // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_RandomStatsConfig                   RandomStatsConfig;                                 // 0x0010(0x0018)(Parm, OutParm, HasGetValueTypeHash)
	TMap<class FString, class FString>            CustomData;                                        // 0x0028(0x0050)(Parm, OutParm)
};
static_assert(alignof(BP_HangarDoor_C_GetItemInfo) == 0x000008, "Wrong alignment on BP_HangarDoor_C_GetItemInfo");
static_assert(sizeof(BP_HangarDoor_C_GetItemInfo) == 0x000078, "Wrong size on BP_HangarDoor_C_GetItemInfo");
static_assert(offsetof(BP_HangarDoor_C_GetItemInfo, Info) == 0x000000, "Member 'BP_HangarDoor_C_GetItemInfo::Info' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_GetItemInfo, Count) == 0x000008, "Member 'BP_HangarDoor_C_GetItemInfo::Count' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_GetItemInfo, RandomStatsConfig) == 0x000010, "Member 'BP_HangarDoor_C_GetItemInfo::RandomStatsConfig' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_GetItemInfo, CustomData) == 0x000028, "Member 'BP_HangarDoor_C_GetItemInfo::CustomData' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.GetJigMultiplayerComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_GetJigMultiplayerComponent final
{
public:
	class UActorComponent*                        JigComp;                                           // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_GetJigMultiplayerComponent) == 0x000008, "Wrong alignment on BP_HangarDoor_C_GetJigMultiplayerComponent");
static_assert(sizeof(BP_HangarDoor_C_GetJigMultiplayerComponent) == 0x000008, "Wrong size on BP_HangarDoor_C_GetJigMultiplayerComponent");
static_assert(offsetof(BP_HangarDoor_C_GetJigMultiplayerComponent, JigComp) == 0x000000, "Member 'BP_HangarDoor_C_GetJigMultiplayerComponent::JigComp' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.GetMainSceneComp
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_GetMainSceneComp final
{
public:
	class USceneComponent*                        Comp;                                              // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_GetMainSceneComp) == 0x000008, "Wrong alignment on BP_HangarDoor_C_GetMainSceneComp");
static_assert(sizeof(BP_HangarDoor_C_GetMainSceneComp) == 0x000008, "Wrong size on BP_HangarDoor_C_GetMainSceneComp");
static_assert(offsetof(BP_HangarDoor_C_GetMainSceneComp, Comp) == 0x000000, "Member 'BP_HangarDoor_C_GetMainSceneComp::Comp' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.JigCanInteract
// 0x0001 (0x0001 - 0x0000)
struct BP_HangarDoor_C_JigCanInteract final
{
public:
	bool                                          Result;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_JigCanInteract) == 0x000001, "Wrong alignment on BP_HangarDoor_C_JigCanInteract");
static_assert(sizeof(BP_HangarDoor_C_JigCanInteract) == 0x000001, "Wrong size on BP_HangarDoor_C_JigCanInteract");
static_assert(offsetof(BP_HangarDoor_C_JigCanInteract, Result) == 0x000000, "Member 'BP_HangarDoor_C_JigCanInteract::Result' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.JigSetCanInteract
// 0x0003 (0x0003 - 0x0000)
struct BP_HangarDoor_C_JigSetCanInteract final
{
public:
	bool                                          CanInteract;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EnablePhysics;                                     // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0002(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_JigSetCanInteract) == 0x000001, "Wrong alignment on BP_HangarDoor_C_JigSetCanInteract");
static_assert(sizeof(BP_HangarDoor_C_JigSetCanInteract) == 0x000003, "Wrong size on BP_HangarDoor_C_JigSetCanInteract");
static_assert(offsetof(BP_HangarDoor_C_JigSetCanInteract, CanInteract) == 0x000000, "Member 'BP_HangarDoor_C_JigSetCanInteract::CanInteract' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_JigSetCanInteract, EnablePhysics) == 0x000001, "Member 'BP_HangarDoor_C_JigSetCanInteract::EnablePhysics' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_JigSetCanInteract, Result) == 0x000002, "Member 'BP_HangarDoor_C_JigSetCanInteract::Result' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.MC_OpenDoor
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_MC_OpenDoor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_MC_OpenDoor) == 0x000008, "Wrong alignment on BP_HangarDoor_C_MC_OpenDoor");
static_assert(sizeof(BP_HangarDoor_C_MC_OpenDoor) == 0x000008, "Wrong size on BP_HangarDoor_C_MC_OpenDoor");
static_assert(offsetof(BP_HangarDoor_C_MC_OpenDoor, Actor) == 0x000000, "Member 'BP_HangarDoor_C_MC_OpenDoor::Actor' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.OnBeginInteract
// 0x0058 (0x0058 - 0x0000)
struct BP_HangarDoor_C_OnBeginInteract final
{
public:
	class AActor*                                 InteractingActor;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMap<struct FGameplayTag, class FText>        Options;                                           // 0x0008(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(BP_HangarDoor_C_OnBeginInteract) == 0x000008, "Wrong alignment on BP_HangarDoor_C_OnBeginInteract");
static_assert(sizeof(BP_HangarDoor_C_OnBeginInteract) == 0x000058, "Wrong size on BP_HangarDoor_C_OnBeginInteract");
static_assert(offsetof(BP_HangarDoor_C_OnBeginInteract, InteractingActor) == 0x000000, "Member 'BP_HangarDoor_C_OnBeginInteract::InteractingActor' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_OnBeginInteract, Options) == 0x000008, "Member 'BP_HangarDoor_C_OnBeginInteract::Options' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.OnExecuteInteract
// 0x0010 (0x0010 - 0x0000)
struct BP_HangarDoor_C_OnExecuteInteract final
{
public:
	class AActor*                                 InteractingActor;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Option;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_OnExecuteInteract) == 0x000008, "Wrong alignment on BP_HangarDoor_C_OnExecuteInteract");
static_assert(sizeof(BP_HangarDoor_C_OnExecuteInteract) == 0x000010, "Wrong size on BP_HangarDoor_C_OnExecuteInteract");
static_assert(offsetof(BP_HangarDoor_C_OnExecuteInteract, InteractingActor) == 0x000000, "Member 'BP_HangarDoor_C_OnExecuteInteract::InteractingActor' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_OnExecuteInteract, Option) == 0x000008, "Member 'BP_HangarDoor_C_OnExecuteInteract::Option' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.OnExecuteInteractDialogue
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_OnExecuteInteractDialogue final
{
public:
	class AActor*                                 InteractingActor;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_OnExecuteInteractDialogue) == 0x000008, "Wrong alignment on BP_HangarDoor_C_OnExecuteInteractDialogue");
static_assert(sizeof(BP_HangarDoor_C_OnExecuteInteractDialogue) == 0x000008, "Wrong size on BP_HangarDoor_C_OnExecuteInteractDialogue");
static_assert(offsetof(BP_HangarDoor_C_OnExecuteInteractDialogue, InteractingActor) == 0x000000, "Member 'BP_HangarDoor_C_OnExecuteInteractDialogue::InteractingActor' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.OnRequestServerInteract
// 0x0048 (0x0048 - 0x0000)
struct BP_HangarDoor_C_OnRequestServerInteract final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Option;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FS_JigPayload                          Payload;                                           // 0x0010(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0040(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_OnRequestServerInteract) == 0x000008, "Wrong alignment on BP_HangarDoor_C_OnRequestServerInteract");
static_assert(sizeof(BP_HangarDoor_C_OnRequestServerInteract) == 0x000048, "Wrong size on BP_HangarDoor_C_OnRequestServerInteract");
static_assert(offsetof(BP_HangarDoor_C_OnRequestServerInteract, Actor) == 0x000000, "Member 'BP_HangarDoor_C_OnRequestServerInteract::Actor' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_OnRequestServerInteract, Option) == 0x000008, "Member 'BP_HangarDoor_C_OnRequestServerInteract::Option' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_OnRequestServerInteract, Payload) == 0x000010, "Member 'BP_HangarDoor_C_OnRequestServerInteract::Payload' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_OnRequestServerInteract, Result) == 0x000040, "Member 'BP_HangarDoor_C_OnRequestServerInteract::Result' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.OnServerExecuteInteract
// 0x0040 (0x0040 - 0x0000)
struct BP_HangarDoor_C_OnServerExecuteInteract final
{
public:
	struct FGameplayTag                           Option;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 ByActor;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FS_JigPayload                          Payload;                                           // 0x0010(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_OnServerExecuteInteract) == 0x000008, "Wrong alignment on BP_HangarDoor_C_OnServerExecuteInteract");
static_assert(sizeof(BP_HangarDoor_C_OnServerExecuteInteract) == 0x000040, "Wrong size on BP_HangarDoor_C_OnServerExecuteInteract");
static_assert(offsetof(BP_HangarDoor_C_OnServerExecuteInteract, Option) == 0x000000, "Member 'BP_HangarDoor_C_OnServerExecuteInteract::Option' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_OnServerExecuteInteract, ByActor) == 0x000008, "Member 'BP_HangarDoor_C_OnServerExecuteInteract::ByActor' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_OnServerExecuteInteract, Payload) == 0x000010, "Member 'BP_HangarDoor_C_OnServerExecuteInteract::Payload' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.OnStopExecuteInteract
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_OnStopExecuteInteract final
{
public:
	class AActor*                                 InteractingActor;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_OnStopExecuteInteract) == 0x000008, "Wrong alignment on BP_HangarDoor_C_OnStopExecuteInteract");
static_assert(sizeof(BP_HangarDoor_C_OnStopExecuteInteract) == 0x000008, "Wrong size on BP_HangarDoor_C_OnStopExecuteInteract");
static_assert(offsetof(BP_HangarDoor_C_OnStopExecuteInteract, InteractingActor) == 0x000000, "Member 'BP_HangarDoor_C_OnStopExecuteInteract::InteractingActor' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.SetInteractOption
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_SetInteractOption final
{
public:
	struct FGameplayTag                           Option;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_SetInteractOption) == 0x000004, "Wrong alignment on BP_HangarDoor_C_SetInteractOption");
static_assert(sizeof(BP_HangarDoor_C_SetInteractOption) == 0x000008, "Wrong size on BP_HangarDoor_C_SetInteractOption");
static_assert(offsetof(BP_HangarDoor_C_SetInteractOption, Option) == 0x000000, "Member 'BP_HangarDoor_C_SetInteractOption::Option' has a wrong offset!");

// Function BP_HangarDoor.BP_HangarDoor_C.SetPickupCount
// 0x0008 (0x0008 - 0x0000)
struct BP_HangarDoor_C_SetPickupCount final
{
public:
	int32                                         NewCount;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0004(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HangarDoor_C_SetPickupCount) == 0x000004, "Wrong alignment on BP_HangarDoor_C_SetPickupCount");
static_assert(sizeof(BP_HangarDoor_C_SetPickupCount) == 0x000008, "Wrong size on BP_HangarDoor_C_SetPickupCount");
static_assert(offsetof(BP_HangarDoor_C_SetPickupCount, NewCount) == 0x000000, "Member 'BP_HangarDoor_C_SetPickupCount::NewCount' has a wrong offset!");
static_assert(offsetof(BP_HangarDoor_C_SetPickupCount, Result) == 0x000004, "Member 'BP_HangarDoor_C_SetPickupCount::Result' has a wrong offset!");

}

