#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InfestationManager

#include "Basic.hpp"

#include "BP_InfestationManager_classes.hpp"
#include "BP_InfestationManager_parameters.hpp"


namespace SDK
{

// Function BP_InfestationManager.BP_InfestationManager_C.CheckAllPrimaryDestroyed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   All_                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InfestationManager_C::CheckAllPrimaryDestroyed(bool* All_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfestationManager_C", "CheckAllPrimaryDestroyed");

	Params::BP_InfestationManager_C_CheckAllPrimaryDestroyed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (All_ != nullptr)
		*All_ = Parms.All_;
}


// Function BP_InfestationManager.BP_InfestationManager_C.ExecuteUbergraph_BP_InfestationManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_InfestationManager_C::ExecuteUbergraph_BP_InfestationManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfestationManager_C", "ExecuteUbergraph_BP_InfestationManager");

	Params::BP_InfestationManager_C_ExecuteUbergraph_BP_InfestationManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InfestationManager.BP_InfestationManager_C.OnCompleted_B3F7F6984C752DC85F8BB59455E585B9
// (BlueprintCallable, BlueprintEvent)

void ABP_InfestationManager_C::OnCompleted_B3F7F6984C752DC85F8BB59455E585B9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfestationManager_C", "OnCompleted_B3F7F6984C752DC85F8BB59455E585B9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InfestationManager.BP_InfestationManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_InfestationManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfestationManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InfestationManager.BP_InfestationManager_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_InfestationManager_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InfestationManager_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

