#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LootContainerWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "InputCore_structs.hpp"


namespace SDK::Params
{

// Function BP_LootContainerWidget.BP_LootContainerWidget_C.ExecuteUbergraph_BP_LootContainerWidget
// 0x0320 (0x0320 - 0x0000)
struct BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FGameplayTag>                   CallFunc_Map_Keys_Keys;                            // 0x0010(0x0010)(ReferenceParm)
	TArray<class FText>                           CallFunc_Map_Values_Values;                        // 0x0020(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Array_Get_Item;                           // 0x0048(0x0018)()
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0060(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_InteractWidgetOption_C*             CallFunc_Create_ReturnValue;                       // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_LootContainers_C> K2Node_DynamicCast_AsBPI_Loot_Containers;          // 0x00B0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsHeld__Held_;                            // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x00C3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPassiveSkillsComponent_C*              CallFunc_GetPassiveSkillsComponent_SkillsComponent; // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_LootContainers_C> K2Node_DynamicCast_AsBPI_Loot_Containers_1;        // 0x00E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F2[0x6];                                       // 0x00F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetSettings_ChanceToProduceNoise;         // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetSettings_Default_ChanceToProduceNoise; // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetSettings_DurationToHold;               // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue;          // 0x0110(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0120(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0128(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsKeyDown_Down;                           // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   CallFunc_GetKey_Key;                               // 0x0150(0x0018)(HasGetValueTypeHash)
	class FText                                   CallFunc_Key_GetDisplayName_ReturnValue;           // 0x0168(0x0018)()
	struct FKey                                   CallFunc_GetKey_Key_1;                             // 0x0180(0x0018)(HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0198(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Key_GetDisplayName_ReturnValue_1;         // 0x01A8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x01C0(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0210(0x0010)(ReferenceParm)
	struct FGameplayTag                           K2Node_CustomEvent_Option_1;                       // 0x0220(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0228(0x0018)()
	TMap<struct FGameplayTag, class FText>        K2Node_CustomEvent_Options;                        // 0x0240(0x0050)(ConstParm)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x0290(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A4[0x4];                                      // 0x02A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_InteractWidgetOption_C*             CallFunc_Array_Get_Item_1;                         // 0x02A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x02B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x02B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B5[0x3];                                      // 0x02B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_InteractWidgetOption_C*             CallFunc_Map_Find_Value;                           // 0x02B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C1[0x3];                                      // 0x02C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           K2Node_CustomEvent_Option;                         // 0x02C4(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CC[0x4];                                      // 0x02CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_NewText;                        // 0x02D0(0x0018)()
	class UBP_InteractWidgetOption_C*             CallFunc_Map_Find_Value_1;                         // 0x02E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x02F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F2[0x2];                                      // 0x02F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x02F4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue;        // 0x0308(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBP_InteractWidgetOption_C*             CallFunc_Array_Get_Item_2;                         // 0x0310(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetPercent_Value_ImplicitCast;            // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget) == 0x000008, "Wrong alignment on BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget");
static_assert(sizeof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget) == 0x000320, "Wrong size on BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, EntryPoint) == 0x000000, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, Temp_int_Variable) == 0x000004, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Map_Keys_Keys) == 0x000010, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Map_Values_Values) == 0x000020, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Map_Values_Values' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, Temp_bool_Has_Been_Initd_Variable) == 0x000034, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, Temp_bool_IsClosed_Variable) == 0x000035, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, Temp_bool_Has_Been_Initd_Variable_1) == 0x000036, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, Temp_int_Loop_Counter_Variable) == 0x000038, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Less_IntInt_ReturnValue) == 0x00003C, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Add_IntInt_ReturnValue_1) == 0x000040, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, Temp_int_Array_Index_Variable) == 0x000044, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Array_Get_Item) == 0x000048, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_Event_MyGeometry) == 0x000060, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_Event_InDeltaTime) == 0x000098, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Create_ReturnValue) == 0x0000A0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x0000A8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_DynamicCast_AsBPI_Loot_Containers) == 0x0000B0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_DynamicCast_AsBPI_Loot_Containers' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_DynamicCast_bSuccess) == 0x0000C0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_IsHeld__Held_) == 0x0000C1, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_IsHeld__Held_' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_IsValid_ReturnValue) == 0x0000C2, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_IsVisible_ReturnValue) == 0x0000C3, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_GetPassiveSkillsComponent_SkillsComponent) == 0x0000C8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_GetPassiveSkillsComponent_SkillsComponent' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, Temp_bool_IsClosed_Variable_1) == 0x0000D0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x0000D8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_DynamicCast_AsBPI_Loot_Containers_1) == 0x0000E0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_DynamicCast_AsBPI_Loot_Containers_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_DynamicCast_bSuccess_1) == 0x0000F0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_IsValid_ReturnValue_1) == 0x0000F1, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_GetSettings_ChanceToProduceNoise) == 0x0000F8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_GetSettings_ChanceToProduceNoise' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_GetSettings_Default_ChanceToProduceNoise) == 0x000100, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_GetSettings_Default_ChanceToProduceNoise' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_GetSettings_DurationToHold) == 0x000108, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_GetSettings_DurationToHold' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Conv_DoubleToString_ReturnValue) == 0x000110, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Conv_DoubleToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_K2_SetTimer_ReturnValue) == 0x000120, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Concat_StrStr_ReturnValue) == 0x000128, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000138, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_IsKeyDown_Down) == 0x000148, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_IsKeyDown_Down' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_GetKey_Key) == 0x000150, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_GetKey_Key' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Key_GetDisplayName_ReturnValue) == 0x000168, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Key_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_GetKey_Key_1) == 0x000180, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_GetKey_Key_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Conv_TextToString_ReturnValue) == 0x000198, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Key_GetDisplayName_ReturnValue_1) == 0x0001A8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Key_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_MakeStruct_FormatArgumentData) == 0x0001C0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_MakeArray_Array) == 0x000210, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_CustomEvent_Option_1) == 0x000220, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_CustomEvent_Option_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Format_ReturnValue) == 0x000228, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_CustomEvent_Options) == 0x000240, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_CustomEvent_Options' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Conv_TextToString_ReturnValue_1) == 0x000290, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Array_Add_ReturnValue) == 0x0002A0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Array_Get_Item_1) == 0x0002A8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Array_Length_ReturnValue_1) == 0x0002B0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Less_IntInt_ReturnValue_1) == 0x0002B4, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Map_Find_Value) == 0x0002B8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Map_Find_ReturnValue) == 0x0002C0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_CustomEvent_Option) == 0x0002C4, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_CustomEvent_Option' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_CustomEvent_NewText) == 0x0002D0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_CustomEvent_NewText' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Map_Find_Value_1) == 0x0002E8, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Map_Find_ReturnValue_1) == 0x0002F0, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_IsValid_ReturnValue_2) == 0x0002F1, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, K2Node_MakeStruct_Margin) == 0x0002F4, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_AddChildToVerticalBox_ReturnValue) == 0x000308, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_AddChildToVerticalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_Array_Get_Item_2) == 0x000310, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget, CallFunc_SetPercent_Value_ImplicitCast) == 0x000318, "Member 'BP_LootContainerWidget_C_ExecuteUbergraph_BP_LootContainerWidget::CallFunc_SetPercent_Value_ImplicitCast' has a wrong offset!");

// Function BP_LootContainerWidget.BP_LootContainerWidget_C.SetOption
// 0x0008 (0x0008 - 0x0000)
struct BP_LootContainerWidget_C_SetOption final
{
public:
	struct FGameplayTag                           Option;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_LootContainerWidget_C_SetOption) == 0x000004, "Wrong alignment on BP_LootContainerWidget_C_SetOption");
static_assert(sizeof(BP_LootContainerWidget_C_SetOption) == 0x000008, "Wrong size on BP_LootContainerWidget_C_SetOption");
static_assert(offsetof(BP_LootContainerWidget_C_SetOption, Option) == 0x000000, "Member 'BP_LootContainerWidget_C_SetOption::Option' has a wrong offset!");

// Function BP_LootContainerWidget.BP_LootContainerWidget_C.SetupWidget
// 0x0050 (0x0050 - 0x0000)
struct BP_LootContainerWidget_C_SetupWidget final
{
public:
	TMap<struct FGameplayTag, class FText>        Options_0;                                         // 0x0000(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(BP_LootContainerWidget_C_SetupWidget) == 0x000008, "Wrong alignment on BP_LootContainerWidget_C_SetupWidget");
static_assert(sizeof(BP_LootContainerWidget_C_SetupWidget) == 0x000050, "Wrong size on BP_LootContainerWidget_C_SetupWidget");
static_assert(offsetof(BP_LootContainerWidget_C_SetupWidget, Options_0) == 0x000000, "Member 'BP_LootContainerWidget_C_SetupWidget::Options_0' has a wrong offset!");

// Function BP_LootContainerWidget.BP_LootContainerWidget_C.Tick
// 0x003C (0x003C - 0x0000)
struct BP_LootContainerWidget_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_LootContainerWidget_C_Tick) == 0x000004, "Wrong alignment on BP_LootContainerWidget_C_Tick");
static_assert(sizeof(BP_LootContainerWidget_C_Tick) == 0x00003C, "Wrong size on BP_LootContainerWidget_C_Tick");
static_assert(offsetof(BP_LootContainerWidget_C_Tick, MyGeometry) == 0x000000, "Member 'BP_LootContainerWidget_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_Tick, InDeltaTime) == 0x000038, "Member 'BP_LootContainerWidget_C_Tick::InDeltaTime' has a wrong offset!");

// Function BP_LootContainerWidget.BP_LootContainerWidget_C.UpdateOptionText
// 0x0020 (0x0020 - 0x0000)
struct BP_LootContainerWidget_C_UpdateOptionText final
{
public:
	struct FGameplayTag                           Option;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class FText                                   NewText;                                           // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(BP_LootContainerWidget_C_UpdateOptionText) == 0x000008, "Wrong alignment on BP_LootContainerWidget_C_UpdateOptionText");
static_assert(sizeof(BP_LootContainerWidget_C_UpdateOptionText) == 0x000020, "Wrong size on BP_LootContainerWidget_C_UpdateOptionText");
static_assert(offsetof(BP_LootContainerWidget_C_UpdateOptionText, Option) == 0x000000, "Member 'BP_LootContainerWidget_C_UpdateOptionText::Option' has a wrong offset!");
static_assert(offsetof(BP_LootContainerWidget_C_UpdateOptionText, NewText) == 0x000008, "Member 'BP_LootContainerWidget_C_UpdateOptionText::NewText' has a wrong offset!");

}

