#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MapData

#include "Basic.hpp"

#include "BP_MapData_classes.hpp"
#include "BP_MapData_parameters.hpp"


namespace SDK
{

// Function BP_MapData.BP_MapData_C.Construct Minimap
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MapData_C::Construct_Minimap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MapData_C", "Construct Minimap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MapData.BP_MapData_C.Update Player Vision
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MapData_C::Update_Player_Vision()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MapData_C", "Update Player Vision");

	UObject::ProcessEvent(Func, nullptr);
}

}

