#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MasterAICharacter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "E_AIBehaviour_structs.hpp"
#include "E_BlockType_structs.hpp"


namespace SDK::Params
{

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.Actor Aim Focus
// 0x0008 (0x0008 - 0x0000)
struct BP_MasterAICharacter_C_Actor_Aim_Focus final
{
public:
	class AActor*                                 Instigator_0;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_Actor_Aim_Focus) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_Actor_Aim_Focus");
static_assert(sizeof(BP_MasterAICharacter_C_Actor_Aim_Focus) == 0x000008, "Wrong size on BP_MasterAICharacter_C_Actor_Aim_Focus");
static_assert(offsetof(BP_MasterAICharacter_C_Actor_Aim_Focus, Instigator_0) == 0x000000, "Member 'BP_MasterAICharacter_C_Actor_Aim_Focus::Instigator_0' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.Actor Attack Target
// 0x0020 (0x0020 - 0x0000)
struct BP_MasterAICharacter_C_Actor_Attack_Target final
{
public:
	class AActor*                                 Attack_Target;                                     // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBP_AIInterface_C>     CallFunc_Actor_Attack_Target_self_CastInput;       // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_Actor_Attack_Target_Attack_Target;        // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_Actor_Attack_Target) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_Actor_Attack_Target");
static_assert(sizeof(BP_MasterAICharacter_C_Actor_Attack_Target) == 0x000020, "Wrong size on BP_MasterAICharacter_C_Actor_Attack_Target");
static_assert(offsetof(BP_MasterAICharacter_C_Actor_Attack_Target, Attack_Target) == 0x000000, "Member 'BP_MasterAICharacter_C_Actor_Attack_Target::Attack_Target' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Actor_Attack_Target, CallFunc_Actor_Attack_Target_self_CastInput) == 0x000008, "Member 'BP_MasterAICharacter_C_Actor_Attack_Target::CallFunc_Actor_Attack_Target_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Actor_Attack_Target, CallFunc_Actor_Attack_Target_Attack_Target) == 0x000018, "Member 'BP_MasterAICharacter_C_Actor_Attack_Target::CallFunc_Actor_Attack_Target_Attack_Target' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.ActorDead?
// 0x0001 (0x0001 - 0x0000)
struct BP_MasterAICharacter_C_ActorDead_ final
{
public:
	bool                                          Dead_;                                             // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_ActorDead_) == 0x000001, "Wrong alignment on BP_MasterAICharacter_C_ActorDead_");
static_assert(sizeof(BP_MasterAICharacter_C_ActorDead_) == 0x000001, "Wrong size on BP_MasterAICharacter_C_ActorDead_");
static_assert(offsetof(BP_MasterAICharacter_C_ActorDead_, Dead_) == 0x000000, "Member 'BP_MasterAICharacter_C_ActorDead_::Dead_' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.AI Alert
// 0x0008 (0x0008 - 0x0000)
struct BP_MasterAICharacter_C_AI_Alert final
{
public:
	class AActor*                                 Alert_Actor;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_AI_Alert) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_AI_Alert");
static_assert(sizeof(BP_MasterAICharacter_C_AI_Alert) == 0x000008, "Wrong size on BP_MasterAICharacter_C_AI_Alert");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Alert, Alert_Actor) == 0x000000, "Member 'BP_MasterAICharacter_C_AI_Alert::Alert_Actor' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.AI Animation Switch
// 0x0001 (0x0001 - 0x0000)
struct BP_MasterAICharacter_C_AI_Animation_Switch final
{
public:
	E_AIBehaviour                                 Behaviour;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_AI_Animation_Switch) == 0x000001, "Wrong alignment on BP_MasterAICharacter_C_AI_Animation_Switch");
static_assert(sizeof(BP_MasterAICharacter_C_AI_Animation_Switch) == 0x000001, "Wrong size on BP_MasterAICharacter_C_AI_Animation_Switch");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Animation_Switch, Behaviour) == 0x000000, "Member 'BP_MasterAICharacter_C_AI_Animation_Switch::Behaviour' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.AI Block
// 0x0010 (0x0010 - 0x0000)
struct BP_MasterAICharacter_C_AI_Block final
{
public:
	E_BlockType                                   Block_Type;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 Block_Attacker;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_AI_Block) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_AI_Block");
static_assert(sizeof(BP_MasterAICharacter_C_AI_Block) == 0x000010, "Wrong size on BP_MasterAICharacter_C_AI_Block");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Block, Block_Type) == 0x000000, "Member 'BP_MasterAICharacter_C_AI_Block::Block_Type' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Block, Block_Attacker) == 0x000008, "Member 'BP_MasterAICharacter_C_AI_Block::Block_Attacker' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.AI Camera Activate
// 0x0001 (0x0001 - 0x0000)
struct BP_MasterAICharacter_C_AI_Camera_Activate final
{
public:
	bool                                          Activate;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_AI_Camera_Activate) == 0x000001, "Wrong alignment on BP_MasterAICharacter_C_AI_Camera_Activate");
static_assert(sizeof(BP_MasterAICharacter_C_AI_Camera_Activate) == 0x000001, "Wrong size on BP_MasterAICharacter_C_AI_Camera_Activate");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Camera_Activate, Activate) == 0x000000, "Member 'BP_MasterAICharacter_C_AI_Camera_Activate::Activate' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.AI Can Interact?
// 0x0020 (0x0020 - 0x0000)
struct BP_MasterAICharacter_C_AI_Can_Interact_ final
{
public:
	bool                                          Can_Interact;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBP_AIInterface_C>     CallFunc_AI_Can_Interact__self_CastInput;          // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_AI_Can_Interact__Can_Interact;            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_AI_Can_Interact_) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_AI_Can_Interact_");
static_assert(sizeof(BP_MasterAICharacter_C_AI_Can_Interact_) == 0x000020, "Wrong size on BP_MasterAICharacter_C_AI_Can_Interact_");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Can_Interact_, Can_Interact) == 0x000000, "Member 'BP_MasterAICharacter_C_AI_Can_Interact_::Can_Interact' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Can_Interact_, CallFunc_AI_Can_Interact__self_CastInput) == 0x000008, "Member 'BP_MasterAICharacter_C_AI_Can_Interact_::CallFunc_AI_Can_Interact__self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Can_Interact_, CallFunc_AI_Can_Interact__Can_Interact) == 0x000018, "Member 'BP_MasterAICharacter_C_AI_Can_Interact_::CallFunc_AI_Can_Interact__Can_Interact' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.Alert Actor Defenders
// 0x0010 (0x0010 - 0x0000)
struct BP_MasterAICharacter_C_Alert_Actor_Defenders final
{
public:
	class AActor*                                 Attacked;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Attacker;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_Alert_Actor_Defenders) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_Alert_Actor_Defenders");
static_assert(sizeof(BP_MasterAICharacter_C_Alert_Actor_Defenders) == 0x000010, "Wrong size on BP_MasterAICharacter_C_Alert_Actor_Defenders");
static_assert(offsetof(BP_MasterAICharacter_C_Alert_Actor_Defenders, Attacked) == 0x000000, "Member 'BP_MasterAICharacter_C_Alert_Actor_Defenders::Attacked' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Alert_Actor_Defenders, Attacker) == 0x000008, "Member 'BP_MasterAICharacter_C_Alert_Actor_Defenders::Attacker' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.Climb Location Movement
// 0x0028 (0x0028 - 0x0000)
struct BP_MasterAICharacter_C_Climb_Location_Movement final
{
public:
	bool                                          Is_Valting;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                End_Climb_Location_0;                              // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Play_Rate;                                         // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_Climb_Location_Movement) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_Climb_Location_Movement");
static_assert(sizeof(BP_MasterAICharacter_C_Climb_Location_Movement) == 0x000028, "Wrong size on BP_MasterAICharacter_C_Climb_Location_Movement");
static_assert(offsetof(BP_MasterAICharacter_C_Climb_Location_Movement, Is_Valting) == 0x000000, "Member 'BP_MasterAICharacter_C_Climb_Location_Movement::Is_Valting' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Climb_Location_Movement, End_Climb_Location_0) == 0x000008, "Member 'BP_MasterAICharacter_C_Climb_Location_Movement::End_Climb_Location_0' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Climb_Location_Movement, Play_Rate) == 0x000020, "Member 'BP_MasterAICharacter_C_Climb_Location_Movement::Play_Rate' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.Debug Text
// 0x0028 (0x0028 - 0x0000)
struct BP_MasterAICharacter_C_Debug_Text final
{
public:
	class FString                                 InString;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	struct FLinearColor                           TextColor;                                         // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PrintString_Duration_ImplicitCast;        // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_Debug_Text) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_Debug_Text");
static_assert(sizeof(BP_MasterAICharacter_C_Debug_Text) == 0x000028, "Wrong size on BP_MasterAICharacter_C_Debug_Text");
static_assert(offsetof(BP_MasterAICharacter_C_Debug_Text, InString) == 0x000000, "Member 'BP_MasterAICharacter_C_Debug_Text::InString' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Debug_Text, TextColor) == 0x000010, "Member 'BP_MasterAICharacter_C_Debug_Text::TextColor' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Debug_Text, CallFunc_PrintString_Duration_ImplicitCast) == 0x000020, "Member 'BP_MasterAICharacter_C_Debug_Text::CallFunc_PrintString_Duration_ImplicitCast' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.ExecuteUbergraph_BP_MasterAICharacter
// 0x0DB0 (0x0DB0 - 0x0000)
struct BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_AIBehaviour                                 K2Node_Event_Behaviour;                            // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_Activate;                             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_BlockType                                   K2Node_Event_Block_Type;                           // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_Block_Attacker;                       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Instigator;                           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBP_AIInterface_C>     CallFunc_Actor_Aim_Focus_self_CastInput;           // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            K2Node_Event_NewController;                        // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_Hit;                                  // 0x0030(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          K2Node_CustomEvent_Is_Valting;                     // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                K2Node_CustomEvent_End_Climb_Location;             // 0x0120(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_Play_Rate;                      // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0140(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate;              // 0x0158(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName EventName, float EmitterTime, int32 ParticleTime, const struct FVector& Location, const struct FVector& Velocity, const struct FVector& Direction, const struct FVector& Normal, class FName BoneName, class UPhysicalMaterial* PhysMat)> K2Node_CreateDelegate_OutputDelegate_1; // 0x0168(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_178[0x8];                                      // 0x0178(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             K2Node_CustomEvent_End_Location;                   // 0x0180(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_Play_Time;                      // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x01F0(0x0060)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Alert_Actor;                          // 0x0250(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBP_AIInterface_C>     K2Node_DynamicCast_AsBP_AIInterface;               // 0x0258(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_Attacked;                             // 0x0270(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Attacker;                             // 0x0278(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentScale_ReturnValue;         // 0x0280(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Event_Argument;                             // 0x02A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UNarrativeComponent*                    CallFunc_GetNarrativeComponent_ReturnValue;        // 0x02B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CompleteNarrativeDataTask_ReturnValue;    // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B9[0x7];                                      // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x02C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0300(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0308(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_TLerp_ReturnValue;                        // 0x0320(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0380(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0398(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x03B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C8[0x8];                                      // 0x03C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x03D0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorTransform_SweepHitResult;      // 0x0430(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorTransform_ReturnValue;         // 0x0518(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_519[0x7];                                      // 0x0519(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0520(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0538(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_539[0x7];                                      // 0x0539(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVector_X_2;                          // 0x0540(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_2;                          // 0x0548(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_2;                          // 0x0550(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_2;        // 0x0558(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue;                        // 0x0570(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x0588(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x0670(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_671[0x7];                                      // 0x0671(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_3;        // 0x0678(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0690(0x0010)(ConstParm, ReferenceParm)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x06A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x06B8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x07A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A1[0x7];                                      // 0x07A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_VLerp_ReturnValue_1;                      // 0x07A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x07C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x07C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C2[0x2];                                      // 0x07C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x07C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x07C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7CC[0x4];                                      // 0x07CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x07D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x07E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0800(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0818(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0830(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0838(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0840(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0848(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x0850(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0858(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x085C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0860(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_864[0x4];                                      // 0x0864(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0868(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0880(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult_1;     // 0x0898(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue_1;        // 0x0980(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_981[0x7];                                      // 0x0981(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0988(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x09A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue_2;                      // 0x09A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult_2;     // 0x09C0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue_2;        // 0x0AA8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0AA9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AAA[0x6];                                      // 0x0AAA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVector_X_3;                          // 0x0AB0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_3;                          // 0x0AB8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_3;                          // 0x0AC0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_4;                          // 0x0AC8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_4;                          // 0x0AD0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_4;                          // 0x0AD8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_ReturnValue;                         // 0x0AE0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_2;                 // 0x0AE8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue_3;                      // 0x0B00(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult_3;     // 0x0B18(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue_3;        // 0x0C00(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetBoolCVar_ReturnValue;                  // 0x0C01(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetBoolCVar_ReturnValue_1;                // 0x0C02(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C03[0x5];                                      // 0x0C03(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0C08(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_4;        // 0x0C10(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0C28(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x0C30(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0C38(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomInteger_ReturnValue;                // 0x0C50(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C54[0x4];                                      // 0x0C54(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0C58(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0C60(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_EventName;                      // 0x0C68(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_EmitterTime;                    // 0x0C70(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ParticleTime;                   // 0x0C74(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Location;                       // 0x0C78(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Velocity;                       // 0x0C90(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Direction;                      // 0x0CA8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Normal;                         // 0x0CC0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_BoneName;                       // 0x0CD8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      K2Node_CustomEvent_PhysMat;                        // 0x0CE0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0CE8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_2;         // 0x0D00(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x0D08(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue_1;        // 0x0D20(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0D38(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0D3C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0D40(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D44[0x4];                                      // 0x0D44(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0D48(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0D50(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UDecalComponent*                        CallFunc_SpawnDecalAtLocation_ReturnValue;         // 0x0D68(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_NewValue;                       // 0x0D70(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D71[0x3];                                      // 0x0D71(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SetPlayRate_NewRate_ImplicitCast;         // 0x0D74(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetPlayRate_NewRate_ImplicitCast_1;       // 0x0D78(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetPlayRate_NewRate_ImplicitCast_2;       // 0x0D7C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_Alpha_ImplicitCast;                  // 0x0D80(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x0D88(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetPlayRate_NewRate_ImplicitCast_3;       // 0x0D90(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D94[0x4];                                      // 0x0D94(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0D98(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SpawnDecalAtLocation_LifeSpan_ImplicitCast; // 0x0DA0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Yaw_ImplicitCast;             // 0x0DA4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0DA8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter) == 0x000010, "Wrong alignment on BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter");
static_assert(sizeof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter) == 0x000DB0, "Wrong size on BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, EntryPoint) == 0x000000, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Behaviour) == 0x000004, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Behaviour' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Activate) == 0x000005, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Activate' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Block_Type) == 0x000006, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Block_Type' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Block_Attacker) == 0x000008, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Block_Attacker' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Instigator) == 0x000010, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Instigator' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Actor_Aim_Focus_self_CastInput) == 0x000018, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Actor_Aim_Focus_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_NewController) == 0x000028, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_NewController' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Hit) == 0x000030, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Hit' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_Is_Valting) == 0x000118, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_Is_Valting' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_End_Climb_Location) == 0x000120, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_End_Climb_Location' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_Play_Rate) == 0x000138, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_Play_Rate' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000140, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CreateDelegate_OutputDelegate) == 0x000158, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CreateDelegate_OutputDelegate_1) == 0x000168, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_End_Location) == 0x000180, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_End_Location' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_Play_Time) == 0x0001E0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_Play_Time' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x0001E8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_GetTransform_ReturnValue) == 0x0001F0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Alert_Actor) == 0x000250, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Alert_Actor' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_DynamicCast_AsBP_AIInterface) == 0x000258, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_DynamicCast_AsBP_AIInterface' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_DynamicCast_bSuccess) == 0x000268, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Attacked) == 0x000270, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Attacked' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Attacker) == 0x000278, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Attacker' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_GetComponentScale_ReturnValue) == 0x000280, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_GetComponentScale_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, Temp_bool_IsClosed_Variable) == 0x000298, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_Event_Argument) == 0x0002A0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_Event_Argument' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_GetNarrativeComponent_ReturnValue) == 0x0002B0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_GetNarrativeComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_CompleteNarrativeDataTask_ReturnValue) == 0x0002B8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_CompleteNarrativeDataTask_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_MakeVector_ReturnValue) == 0x0002C0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_X) == 0x0002D8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Y) == 0x0002E0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Z) == 0x0002E8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_X_1) == 0x0002F0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Y_1) == 0x0002F8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Z_1) == 0x000300, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_MakeVector_ReturnValue_1) == 0x000308, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_TLerp_ReturnValue) == 0x000320, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_TLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakTransform_Location) == 0x000380, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakTransform_Rotation) == 0x000398, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakTransform_Scale) == 0x0003B0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_MakeTransform_ReturnValue) == 0x0003D0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorTransform_SweepHitResult) == 0x000430, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorTransform_ReturnValue) == 0x000518, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000520, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, Temp_bool_Has_Been_Initd_Variable) == 0x000538, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_X_2) == 0x000540, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_X_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Y_2) == 0x000548, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Y_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Z_2) == 0x000550, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Z_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_GetActorLocation_ReturnValue_2) == 0x000558, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_GetActorLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_VLerp_ReturnValue) == 0x000570, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_VLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x000588, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_ReturnValue) == 0x000670, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_GetActorLocation_ReturnValue_3) == 0x000678, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_GetActorLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_MakeArray_Array) == 0x000690, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0006A0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_LineTraceSingle_OutHit) == 0x0006B8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_LineTraceSingle_ReturnValue) == 0x0007A0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_VLerp_ReturnValue_1) == 0x0007A8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_VLerp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_bBlockingHit) == 0x0007C0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_bInitialOverlap) == 0x0007C1, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_Time) == 0x0007C4, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_Distance) == 0x0007C8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_Location) == 0x0007D0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_ImpactPoint) == 0x0007E8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_Normal) == 0x000800, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_ImpactNormal) == 0x000818, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_PhysMat) == 0x000830, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_HitActor) == 0x000838, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_HitComponent) == 0x000840, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_HitBoneName) == 0x000848, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_BoneName) == 0x000850, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_HitItem) == 0x000858, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_ElementIndex) == 0x00085C, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_FaceIndex) == 0x000860, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_TraceStart) == 0x000868, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakHitResult_TraceEnd) == 0x000880, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_SweepHitResult_1) == 0x000898, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_ReturnValue_1) == 0x000980, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Add_VectorVector_ReturnValue) == 0x000988, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x0009A0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_VLerp_ReturnValue_2) == 0x0009A8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_VLerp_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_SweepHitResult_2) == 0x0009C0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_SweepHitResult_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_ReturnValue_2) == 0x000AA8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000AA9, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_X_3) == 0x000AB0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_X_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Y_3) == 0x000AB8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Y_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Z_3) == 0x000AC0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Z_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_X_4) == 0x000AC8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_X_4' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Y_4) == 0x000AD0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Y_4' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakVector_Z_4) == 0x000AD8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakVector_Z_4' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Lerp_ReturnValue) == 0x000AE0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Lerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_MakeVector_ReturnValue_2) == 0x000AE8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_MakeVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_VLerp_ReturnValue_3) == 0x000B00, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_VLerp_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_SweepHitResult_3) == 0x000B18, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_SweepHitResult_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_SetActorLocation_ReturnValue_3) == 0x000C00, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_SetActorLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_GetBoolCVar_ReturnValue) == 0x000C01, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_GetBoolCVar_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_GetBoolCVar_ReturnValue_1) == 0x000C02, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_GetBoolCVar_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SelectFloat_ReturnValue) == 0x000C08, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_K2_GetActorLocation_ReturnValue_4) == 0x000C10, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_K2_GetActorLocation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_RandomFloatInRange_ReturnValue) == 0x000C28, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x000C30, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x000C38, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_RandomInteger_ReturnValue) == 0x000C50, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_RandomInteger_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000C58, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000C60, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_EventName) == 0x000C68, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_EventName' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_EmitterTime) == 0x000C70, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_EmitterTime' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_ParticleTime) == 0x000C74, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_ParticleTime' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_Location) == 0x000C78, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_Location' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_Velocity) == 0x000C90, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_Velocity' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_Direction) == 0x000CA8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_Direction' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_Normal) == 0x000CC0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_Normal' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_BoneName) == 0x000CD8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_BoneName' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_PhysMat) == 0x000CE0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000CE8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_RandomFloatInRange_ReturnValue_2) == 0x000D00, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_RandomFloatInRange_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x000D08, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Conv_DoubleToVector_ReturnValue_1) == 0x000D20, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Conv_DoubleToVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakRotator_Roll) == 0x000D38, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakRotator_Pitch) == 0x000D3C, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_BreakRotator_Yaw) == 0x000D40, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000D48, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_MakeRotator_ReturnValue) == 0x000D50, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SpawnDecalAtLocation_ReturnValue) == 0x000D68, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SpawnDecalAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, K2Node_CustomEvent_NewValue) == 0x000D70, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::K2Node_CustomEvent_NewValue' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SetPlayRate_NewRate_ImplicitCast) == 0x000D74, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SetPlayRate_NewRate_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SetPlayRate_NewRate_ImplicitCast_1) == 0x000D78, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SetPlayRate_NewRate_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SetPlayRate_NewRate_ImplicitCast_2) == 0x000D7C, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SetPlayRate_NewRate_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Lerp_Alpha_ImplicitCast) == 0x000D80, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Lerp_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Divide_DoubleDouble_A_ImplicitCast) == 0x000D88, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Divide_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SetPlayRate_NewRate_ImplicitCast_3) == 0x000D90, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SetPlayRate_NewRate_ImplicitCast_3' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_Greater_DoubleDouble_A_ImplicitCast) == 0x000D98, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_Greater_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SpawnDecalAtLocation_LifeSpan_ImplicitCast) == 0x000DA0, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SpawnDecalAtLocation_LifeSpan_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_MakeRotator_Yaw_ImplicitCast) == 0x000DA4, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_MakeRotator_Yaw_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter, CallFunc_SetScalarParameterValue_Value_ImplicitCast) == 0x000DA8, "Member 'BP_MasterAICharacter_C_ExecuteUbergraph_BP_MasterAICharacter::CallFunc_SetScalarParameterValue_Value_ImplicitCast' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.GetQuestArgument
// 0x0010 (0x0010 - 0x0000)
struct BP_MasterAICharacter_C_GetQuestArgument final
{
public:
	class FString                                 Argument;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_GetQuestArgument) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_GetQuestArgument");
static_assert(sizeof(BP_MasterAICharacter_C_GetQuestArgument) == 0x000010, "Wrong size on BP_MasterAICharacter_C_GetQuestArgument");
static_assert(offsetof(BP_MasterAICharacter_C_GetQuestArgument, Argument) == 0x000000, "Member 'BP_MasterAICharacter_C_GetQuestArgument::Argument' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.OnCollide
// 0x0080 (0x0080 - 0x0000)
struct BP_MasterAICharacter_C_OnCollide final
{
public:
	class FName                                   EventName;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EmitterTime;                                       // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ParticleTime;                                      // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Location;                                          // 0x0010(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Velocity;                                          // 0x0028(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Direction;                                         // 0x0040(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Normal;                                            // 0x0058(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   BoneName;                                          // 0x0070(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      PhysMat;                                           // 0x0078(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_OnCollide) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_OnCollide");
static_assert(sizeof(BP_MasterAICharacter_C_OnCollide) == 0x000080, "Wrong size on BP_MasterAICharacter_C_OnCollide");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, EventName) == 0x000000, "Member 'BP_MasterAICharacter_C_OnCollide::EventName' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, EmitterTime) == 0x000008, "Member 'BP_MasterAICharacter_C_OnCollide::EmitterTime' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, ParticleTime) == 0x00000C, "Member 'BP_MasterAICharacter_C_OnCollide::ParticleTime' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, Location) == 0x000010, "Member 'BP_MasterAICharacter_C_OnCollide::Location' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, Velocity) == 0x000028, "Member 'BP_MasterAICharacter_C_OnCollide::Velocity' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, Direction) == 0x000040, "Member 'BP_MasterAICharacter_C_OnCollide::Direction' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, Normal) == 0x000058, "Member 'BP_MasterAICharacter_C_OnCollide::Normal' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, BoneName) == 0x000070, "Member 'BP_MasterAICharacter_C_OnCollide::BoneName' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_OnCollide, PhysMat) == 0x000078, "Member 'BP_MasterAICharacter_C_OnCollide::PhysMat' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.OnLanded
// 0x00E8 (0x00E8 - 0x0000)
struct BP_MasterAICharacter_C_OnLanded final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_MasterAICharacter_C_OnLanded) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_OnLanded");
static_assert(sizeof(BP_MasterAICharacter_C_OnLanded) == 0x0000E8, "Wrong size on BP_MasterAICharacter_C_OnLanded");
static_assert(offsetof(BP_MasterAICharacter_C_OnLanded, Hit) == 0x000000, "Member 'BP_MasterAICharacter_C_OnLanded::Hit' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.ReceivePossessed
// 0x0008 (0x0008 - 0x0000)
struct BP_MasterAICharacter_C_ReceivePossessed final
{
public:
	class AController*                            NewController;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_ReceivePossessed) == 0x000008, "Wrong alignment on BP_MasterAICharacter_C_ReceivePossessed");
static_assert(sizeof(BP_MasterAICharacter_C_ReceivePossessed) == 0x000008, "Wrong size on BP_MasterAICharacter_C_ReceivePossessed");
static_assert(offsetof(BP_MasterAICharacter_C_ReceivePossessed, NewController) == 0x000000, "Member 'BP_MasterAICharacter_C_ReceivePossessed::NewController' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.Smooth Move AI Actor
// 0x0070 (0x0070 - 0x0000)
struct BP_MasterAICharacter_C_Smooth_Move_AI_Actor final
{
public:
	struct FTransform                             End_Location_0;                                    // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Play_Time;                                         // 0x0060(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_Smooth_Move_AI_Actor) == 0x000010, "Wrong alignment on BP_MasterAICharacter_C_Smooth_Move_AI_Actor");
static_assert(sizeof(BP_MasterAICharacter_C_Smooth_Move_AI_Actor) == 0x000070, "Wrong size on BP_MasterAICharacter_C_Smooth_Move_AI_Actor");
static_assert(offsetof(BP_MasterAICharacter_C_Smooth_Move_AI_Actor, End_Location_0) == 0x000000, "Member 'BP_MasterAICharacter_C_Smooth_Move_AI_Actor::End_Location_0' has a wrong offset!");
static_assert(offsetof(BP_MasterAICharacter_C_Smooth_Move_AI_Actor, Play_Time) == 0x000060, "Member 'BP_MasterAICharacter_C_Smooth_Move_AI_Actor::Play_Time' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.XP
// 0x0001 (0x0001 - 0x0000)
struct BP_MasterAICharacter_C_XP final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_XP) == 0x000001, "Wrong alignment on BP_MasterAICharacter_C_XP");
static_assert(sizeof(BP_MasterAICharacter_C_XP) == 0x000001, "Wrong size on BP_MasterAICharacter_C_XP");
static_assert(offsetof(BP_MasterAICharacter_C_XP, NewValue) == 0x000000, "Member 'BP_MasterAICharacter_C_XP::NewValue' has a wrong offset!");

// Function BP_MasterAICharacter.BP_MasterAICharacter_C.AI Is Dead?
// 0x0001 (0x0001 - 0x0000)
struct BP_MasterAICharacter_C_AI_Is_Dead_ final
{
public:
	bool                                          Dead;                                              // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MasterAICharacter_C_AI_Is_Dead_) == 0x000001, "Wrong alignment on BP_MasterAICharacter_C_AI_Is_Dead_");
static_assert(sizeof(BP_MasterAICharacter_C_AI_Is_Dead_) == 0x000001, "Wrong size on BP_MasterAICharacter_C_AI_Is_Dead_");
static_assert(offsetof(BP_MasterAICharacter_C_AI_Is_Dead_, Dead) == 0x000000, "Member 'BP_MasterAICharacter_C_AI_Is_Dead_::Dead' has a wrong offset!");

}

