#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_POIManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "RandomContainerItem_structs.hpp"
#include "S_MarkerData_structs.hpp"


namespace SDK::Params
{

// Function BP_POIManager.BP_POIManager_C.CheckLoc
// 0x0120 (0x0120 - 0x0000)
struct BP_POIManager_C_CheckLoc final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0008(0x0010)(ConstParm, ReferenceParm)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_SphereTraceSingle_OutHit;                 // 0x0030(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_SphereTraceSingle_ReturnValue;            // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_POIManager_C_CheckLoc) == 0x000008, "Wrong alignment on BP_POIManager_C_CheckLoc");
static_assert(sizeof(BP_POIManager_C_CheckLoc) == 0x000120, "Wrong size on BP_POIManager_C_CheckLoc");
static_assert(offsetof(BP_POIManager_C_CheckLoc, ReturnValue) == 0x000000, "Member 'BP_POIManager_C_CheckLoc::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_CheckLoc, Temp_object_Variable) == 0x000008, "Member 'BP_POIManager_C_CheckLoc::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_CheckLoc, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000018, "Member 'BP_POIManager_C_CheckLoc::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_CheckLoc, CallFunc_SphereTraceSingle_OutHit) == 0x000030, "Member 'BP_POIManager_C_CheckLoc::CallFunc_SphereTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_CheckLoc, CallFunc_SphereTraceSingle_ReturnValue) == 0x000118, "Member 'BP_POIManager_C_CheckLoc::CallFunc_SphereTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_CheckLoc, CallFunc_Not_PreBool_ReturnValue) == 0x000119, "Member 'BP_POIManager_C_CheckLoc::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function BP_POIManager.BP_POIManager_C.ComponentsToSave
// 0x0010 (0x0010 - 0x0000)
struct BP_POIManager_C_ComponentsToSave final
{
public:
	TArray<class UActorComponent*>                Components;                                        // 0x0000(0x0010)(Parm, OutParm, ContainsInstancedReference)
};
static_assert(alignof(BP_POIManager_C_ComponentsToSave) == 0x000008, "Wrong alignment on BP_POIManager_C_ComponentsToSave");
static_assert(sizeof(BP_POIManager_C_ComponentsToSave) == 0x000010, "Wrong size on BP_POIManager_C_ComponentsToSave");
static_assert(offsetof(BP_POIManager_C_ComponentsToSave, Components) == 0x000000, "Member 'BP_POIManager_C_ComponentsToSave::Components' has a wrong offset!");

// Function BP_POIManager.BP_POIManager_C.DistanceCheck
// 0x0048 (0x0048 - 0x0000)
struct BP_POIManager_C_DistanceCheck final
{
public:
	class ULevellingComponent_C*                  CallFunc_GetLevellingComponent_LevellingComponent; // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AHUD_Game_C*                            CallFunc_GetGameHUD_HUD;                           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_XpMultiplierCalc_ReturnValue;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_AddXP_XPOutput;                           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetDistanceTo_ReturnValue;                // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36[0x2];                                       // 0x0036(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_B_ImplicitCast;         // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_POIManager_C_DistanceCheck) == 0x000008, "Wrong alignment on BP_POIManager_C_DistanceCheck");
static_assert(sizeof(BP_POIManager_C_DistanceCheck) == 0x000048, "Wrong size on BP_POIManager_C_DistanceCheck");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_GetLevellingComponent_LevellingComponent) == 0x000000, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_GetLevellingComponent_LevellingComponent' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_GetGameHUD_HUD) == 0x000008, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_GetGameHUD_HUD' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_SelectFloat_ReturnValue) == 0x000010, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_XpMultiplierCalc_ReturnValue) == 0x000018, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_XpMultiplierCalc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_AddXP_XPOutput) == 0x000020, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_AddXP_XPOutput' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_GetPlayerCharacter_ReturnValue) == 0x000028, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_GetPlayerCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_GetDistanceTo_ReturnValue) == 0x000030, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_GetDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_IsValid_ReturnValue) == 0x000034, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000035, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_Less_DoubleDouble_B_ImplicitCast) == 0x000038, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_Less_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_DistanceCheck, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x000040, "Member 'BP_POIManager_C_DistanceCheck::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BP_POIManager.BP_POIManager_C.ExecuteUbergraph_BP_POIManager
// 0x0A50 (0x0A50 - 0x0000)
struct BP_POIManager_C_ExecuteUbergraph_BP_POIManager final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0020(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable;                              // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_1;                            // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Temp_struct_Variable_2;                            // 0x0068(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_3;                            // 0x0078(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0094(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_95[0x3];                                       // 0x0095(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_1;            // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x00B8(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0108(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0158(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0168(0x0018)()
	class UBPC_MinimapSystem_C*                   CallFunc_Get_Minimap_Component_ReturnValue;        // 0x0180(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0189(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18A[0x6];                                      // 0x018A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              K2Node_Select_Default;                             // 0x0190(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              K2Node_Select_Default_1;                           // 0x01A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x01B0(0x0018)()
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x01C8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array_1;                          // 0x01E0(0x0010)(ConstParm, ReferenceParm)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRandomContainerItem                   CallFunc_Array_Get_Item;                           // 0x01F8(0x0058)(HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0250(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_2;         // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_271[0x3];                                      // 0x0271(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0274(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_284[0x4];                                      // 0x0284(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0288(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x02A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x02B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x02D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x02E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x02EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x02F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F4[0x4];                                      // 0x02F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x02F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0310(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_XpMultiplierCalc_ReturnValue;             // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0320(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ULevellingComponent_C*                  CallFunc_GetLevellingComponent_LevellingComponent; // 0x0338(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0340(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_AddXP_XPOutput;                           // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x03A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AContainer_CompoundCrate_C*             CallFunc_FinishSpawningActor_ReturnValue;          // 0x03B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x03B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_4;                            // 0x03D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location_1;                // 0x03E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation_1;                // 0x03F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale_1;                   // 0x0410(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x0428(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0440(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_444[0xC];                                      // 0x0444(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x0450(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x04B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x04B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B9[0x7];                                      // 0x04B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AContainer_POICrate_C*                  CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x04C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x04C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CC[0x4];                                      // 0x04CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_2;            // 0x04D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x04D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D9[0x7];                                      // 0x04D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x04E0(0x0050)(HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0530(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x0534(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_3;            // 0x0538(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x0540(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_2;                          // 0x0590(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x05A0(0x0018)()
	struct FLinearColor                           Temp_struct_Variable_5;                            // 0x05B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnyInvokerInRadius_Result;              // 0x05C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x05C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5CA[0x2];                                      // 0x05CA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x05CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_4;            // 0x05D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_1;                      // 0x05D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5DC[0x4];                                      // 0x05DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_4;            // 0x05E0(0x0050)(HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_5;            // 0x0630(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_5;            // 0x0638(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_3;                          // 0x0688(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_2;                     // 0x0698(0x0018)()
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x06B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckLoc_ReturnValue;                     // 0x06B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x06B5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6B6[0x2];                                      // 0x06B6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetFloatCVar_ReturnValue;                 // 0x06B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6BC[0x4];                                      // 0x06BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x06C0(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FHitResult>                     CallFunc_SphereTraceMultiForObjects_OutHits;       // 0x06D0(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_SphereTraceMultiForObjects_ReturnValue;   // 0x06E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6E1[0x7];                                      // 0x06E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item_1;                         // 0x06E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_Array_Get_Item_2;                         // 0x06F8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x07E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x07E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x07E5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7E6[0x2];                                      // 0x07E6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x07E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x07EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x07F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0808(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0820(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0838(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0850(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0858(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0860(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0868(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x0870(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0878(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x087C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0880(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_884[0x4];                                      // 0x0884(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0888(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x08A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x08B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x08B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8BA[0x6];                                      // 0x08BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_JigMultiplayer_C*                   CallFunc_GetComponentByClass_ReturnValue;          // 0x08C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x08C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C9[0x3];                                      // 0x08C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x08CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x08D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x08D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8D2[0x2];                                      // 0x08D2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x08D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_2;                           // 0x08D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FS_MarkerData                          K2Node_MakeStruct_S_MarkerData;                    // 0x08E8(0x0070)(HasGetValueTypeHash)
	class UW_POIMarker_C*                         CallFunc_Add_POI_Marker_Markers;                   // 0x0958(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_RandomiseSpawn_Transform;                 // 0x0960(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_Array_Get_Item_3;                         // 0x09C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x09C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C9[0x7];                                      // 0x09C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2; // 0x09D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue_2;        // 0x09D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_AI_C>             K2Node_DynamicCast_AsBPI_AI;                       // 0x09E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x09F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9F1[0x7];                                      // 0x09F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USD_AIComponent_C*                      CallFunc_GetComponentByClass_ReturnValue_1;        // 0x09F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_ZombieBoss_C*                       K2Node_DynamicCast_AsBP_Zombie_Boss;               // 0x0A00(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0A08(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A09[0x7];                                      // 0x0A09(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue_3;         // 0x0A10(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatCVar_ReturnValue_1;               // 0x0A18(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1C[0x4];                                      // 0x0A1C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0A20(0x0008)(NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0A28(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0A30(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_K2_SetTimer_Time_ImplicitCast;            // 0x0A34(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_A_ImplicitCast;     // 0x0A38(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Yaw_ImplicitCast;             // 0x0A40(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_K2_SetTimerDelegate_Time_ImplicitCast;    // 0x0A44(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x0A48(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager) == 0x000010, "Wrong alignment on BP_POIManager_C_ExecuteUbergraph_BP_POIManager");
static_assert(sizeof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager) == 0x000A50, "Wrong size on BP_POIManager_C_ExecuteUbergraph_BP_POIManager");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, EntryPoint) == 0x000000, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000008, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_CreateDelegate_OutputDelegate_1) == 0x000020, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_struct_Variable) == 0x000030, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_struct_Variable_1) == 0x000040, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_int_Array_Index_Variable) == 0x000050, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_int_Loop_Counter_Variable) == 0x000054, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Add_IntInt_ReturnValue) == 0x000058, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_int_Array_Index_Variable_1) == 0x00005C, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_bool_Variable) == 0x000060, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_struct_Variable_2) == 0x000068, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_struct_Variable_3) == 0x000078, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_struct_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_int_Variable) == 0x000088, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Add_IntInt_ReturnValue_1) == 0x00008C, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_int_Variable_1) == 0x000090, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_bool_Variable_1) == 0x000094, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_GetPlayerCharacter_ReturnValue) == 0x000098, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_GetPlayerCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_IsValid_ReturnValue) == 0x0000A0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_IntToInt64_ReturnValue) == 0x0000A8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_IntToInt64_ReturnValue_1) == 0x0000B0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_IntToInt64_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeStruct_FormatArgumentData) == 0x0000B8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeStruct_FormatArgumentData_1) == 0x000108, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeArray_Array) == 0x000158, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Format_ReturnValue) == 0x000168, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Get_Minimap_Component_ReturnValue) == 0x000180, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Get_Minimap_Component_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BooleanOR_ReturnValue) == 0x000188, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Greater_IntInt_ReturnValue) == 0x000189, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_Select_Default) == 0x000190, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_Select_Default_1) == 0x0001A0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_StringToText_ReturnValue) == 0x0001B0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0001C8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeArray_Array_1) == 0x0001E0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_RandomFloatInRange_ReturnValue) == 0x0001F0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_Get_Item) == 0x0001F8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_K2_SetTimer_ReturnValue) == 0x000250, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_Length_ReturnValue) == 0x000258, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x000260, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_RandomFloatInRange_ReturnValue_2) == 0x000268, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_RandomFloatInRange_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x000270, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_CreateDelegate_OutputDelegate_2) == 0x000274, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000288, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakTransform_Location) == 0x0002A0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakTransform_Rotation) == 0x0002B8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakTransform_Scale) == 0x0002D0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakRotator_Roll) == 0x0002E8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakRotator_Pitch) == 0x0002EC, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakRotator_Yaw) == 0x0002F0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Add_VectorVector_ReturnValue) == 0x0002F8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000310, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_XpMultiplierCalc_ReturnValue) == 0x000318, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_XpMultiplierCalc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_MakeRotator_ReturnValue) == 0x000320, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_GetLevellingComponent_LevellingComponent) == 0x000338, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_GetLevellingComponent_LevellingComponent' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_MakeTransform_ReturnValue) == 0x000340, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_AddXP_XPOutput) == 0x0003A0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_AddXP_XPOutput' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0003A8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_FinishSpawningActor_ReturnValue) == 0x0003B0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x0003B8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_struct_Variable_4) == 0x0003D0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_struct_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakTransform_Location_1) == 0x0003E0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakTransform_Location_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakTransform_Rotation_1) == 0x0003F8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakTransform_Rotation_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakTransform_Scale_1) == 0x000410, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakTransform_Scale_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Add_VectorVector_ReturnValue_1) == 0x000428, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_int_Variable_2) == 0x000440, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_MakeTransform_ReturnValue_1) == 0x000450, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x0004B0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_IsValid_ReturnValue_1) == 0x0004B8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x0004C0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_int_Loop_Counter_Variable_1) == 0x0004C8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_IntToInt64_ReturnValue_2) == 0x0004D0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_IntToInt64_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Less_IntInt_ReturnValue) == 0x0004D8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeStruct_FormatArgumentData_2) == 0x0004E0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Add_IntInt_ReturnValue_2) == 0x000530, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Clamp_ReturnValue) == 0x000534, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_IntToInt64_ReturnValue_3) == 0x000538, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_IntToInt64_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeStruct_FormatArgumentData_3) == 0x000540, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeStruct_FormatArgumentData_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeArray_Array_2) == 0x000590, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Format_ReturnValue_1) == 0x0005A0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_struct_Variable_5) == 0x0005B8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_struct_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_IsAnyInvokerInRadius_Result) == 0x0005C8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_IsAnyInvokerInRadius_Result' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Greater_IntInt_ReturnValue_1) == 0x0005C9, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Subtract_IntInt_ReturnValue) == 0x0005CC, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_IntToInt64_ReturnValue_4) == 0x0005D0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_IntToInt64_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Clamp_ReturnValue_1) == 0x0005D8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Clamp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeStruct_FormatArgumentData_4) == 0x0005E0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeStruct_FormatArgumentData_4' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Conv_IntToInt64_ReturnValue_5) == 0x000630, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Conv_IntToInt64_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeStruct_FormatArgumentData_5) == 0x000638, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeStruct_FormatArgumentData_5' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeArray_Array_3) == 0x000688, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeArray_Array_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Format_ReturnValue_2) == 0x000698, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Format_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Add_IntInt_ReturnValue_3) == 0x0006B0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_CheckLoc_ReturnValue) == 0x0006B4, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_CheckLoc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BooleanOR_ReturnValue_1) == 0x0006B5, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_GetFloatCVar_ReturnValue) == 0x0006B8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_GetFloatCVar_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_object_Variable) == 0x0006C0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_SphereTraceMultiForObjects_OutHits) == 0x0006D0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_SphereTraceMultiForObjects_OutHits' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_SphereTraceMultiForObjects_ReturnValue) == 0x0006E0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_SphereTraceMultiForObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_Get_Item_1) == 0x0006E8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_Get_Item_2) == 0x0006F8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_Length_ReturnValue_1) == 0x0007E0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_bBlockingHit) == 0x0007E4, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_bInitialOverlap) == 0x0007E5, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_Time) == 0x0007E8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_Distance) == 0x0007EC, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_Location) == 0x0007F0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_ImpactPoint) == 0x000808, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_Normal) == 0x000820, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_ImpactNormal) == 0x000838, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_PhysMat) == 0x000850, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_HitActor) == 0x000858, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_HitComponent) == 0x000860, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_HitBoneName) == 0x000868, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_BoneName) == 0x000870, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_HitItem) == 0x000878, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_ElementIndex) == 0x00087C, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_FaceIndex) == 0x000880, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_TraceStart) == 0x000888, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BreakHitResult_TraceEnd) == 0x0008A0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Less_IntInt_ReturnValue_1) == 0x0008B8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_IsValid_ReturnValue_2) == 0x0008B9, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_GetComponentByClass_ReturnValue) == 0x0008C0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_IsValid_ReturnValue_3) == 0x0008C8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x0008CC, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_LessEqual_IntInt_ReturnValue) == 0x0008D0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, Temp_bool_Variable_2) == 0x0008D1, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_AddUnique_ReturnValue) == 0x0008D4, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_Select_Default_2) == 0x0008D8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_MakeStruct_S_MarkerData) == 0x0008E8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_MakeStruct_S_MarkerData' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Add_POI_Marker_Markers) == 0x000958, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Add_POI_Marker_Markers' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_RandomiseSpawn_Transform) == 0x000960, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_RandomiseSpawn_Transform' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_Get_Item_3) == 0x0009C0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Array_IsValidIndex_ReturnValue) == 0x0009C8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2) == 0x0009D0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_FinishSpawningActor_ReturnValue_2) == 0x0009D8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_FinishSpawningActor_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_DynamicCast_AsBPI_AI) == 0x0009E0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_DynamicCast_AsBPI_AI' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_DynamicCast_bSuccess) == 0x0009F0, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_GetComponentByClass_ReturnValue_1) == 0x0009F8, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_GetComponentByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_DynamicCast_AsBP_Zombie_Boss) == 0x000A00, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_DynamicCast_AsBP_Zombie_Boss' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, K2Node_DynamicCast_bSuccess_1) == 0x000A08, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_RandomFloatInRange_ReturnValue_3) == 0x000A10, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_RandomFloatInRange_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_GetFloatCVar_ReturnValue_1) == 0x000A18, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_GetFloatCVar_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000A20, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000A28, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_FTrunc_ReturnValue) == 0x000A30, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_K2_SetTimer_Time_ImplicitCast) == 0x000A34, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_K2_SetTimer_Time_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Subtract_DoubleDouble_A_ImplicitCast) == 0x000A38, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Subtract_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_MakeRotator_Yaw_ImplicitCast) == 0x000A40, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_MakeRotator_Yaw_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_K2_SetTimerDelegate_Time_ImplicitCast) == 0x000A44, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_K2_SetTimerDelegate_Time_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_ExecuteUbergraph_BP_POIManager, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x000A48, "Member 'BP_POIManager_C_ExecuteUbergraph_BP_POIManager::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");

// Function BP_POIManager.BP_POIManager_C.IsAnyInvokerInRadius
// 0x0050 (0x0050 - 0x0000)
struct BP_POIManager_C_IsAnyInvokerInRadius final
{
public:
	double                                        Radius;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         L_GameState;                                       // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Square_ReturnValue;                       // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAIOptimizerSubsystem*                  CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetDistanceToClosestInvokerSquared_ReturnValue; // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_LessEqual_DoubleDouble_A_ImplicitCast;    // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_POIManager_C_IsAnyInvokerInRadius) == 0x000008, "Wrong alignment on BP_POIManager_C_IsAnyInvokerInRadius");
static_assert(sizeof(BP_POIManager_C_IsAnyInvokerInRadius) == 0x000050, "Wrong size on BP_POIManager_C_IsAnyInvokerInRadius");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, Radius) == 0x000000, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::Radius' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, Result) == 0x000008, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::Result' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, L_GameState) == 0x000010, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::L_GameState' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000018, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, CallFunc_Square_ReturnValue) == 0x000030, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::CallFunc_Square_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, CallFunc_GetWorldSubsystem_ReturnValue) == 0x000038, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::CallFunc_GetWorldSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, CallFunc_GetDistanceToClosestInvokerSquared_ReturnValue) == 0x000040, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::CallFunc_GetDistanceToClosestInvokerSquared_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x000044, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_IsAnyInvokerInRadius, CallFunc_LessEqual_DoubleDouble_A_ImplicitCast) == 0x000048, "Member 'BP_POIManager_C_IsAnyInvokerInRadius::CallFunc_LessEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BP_POIManager.BP_POIManager_C.RandomiseSpawn
// 0x0160 (0x0160 - 0x0000)
struct BP_POIManager_C_RandomiseSpawn final
{
public:
	class USceneComponent*                        SceneComp;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Transform;                                         // 0x0010(0x0060)(Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0070(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0088(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_RandomPointInBoundingBox_ReturnValue;     // 0x00A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_RandomRotator_ReturnValue;                // 0x00B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x00E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F8[0x8];                                       // 0x00F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0100(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_POIManager_C_RandomiseSpawn) == 0x000010, "Wrong alignment on BP_POIManager_C_RandomiseSpawn");
static_assert(sizeof(BP_POIManager_C_RandomiseSpawn) == 0x000160, "Wrong size on BP_POIManager_C_RandomiseSpawn");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, SceneComp) == 0x000000, "Member 'BP_POIManager_C_RandomiseSpawn::SceneComp' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, Transform) == 0x000010, "Member 'BP_POIManager_C_RandomiseSpawn::Transform' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000070, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_MakeVector_ReturnValue) == 0x000088, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_RandomPointInBoundingBox_ReturnValue) == 0x0000A0, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_RandomPointInBoundingBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_RandomRotator_ReturnValue) == 0x0000B8, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_RandomRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_BreakRotator_Roll) == 0x0000D0, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_BreakRotator_Pitch) == 0x0000D4, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_BreakRotator_Yaw) == 0x0000D8, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_MakeRotator_ReturnValue) == 0x0000E0, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_RandomiseSpawn, CallFunc_MakeTransform_ReturnValue) == 0x000100, "Member 'BP_POIManager_C_RandomiseSpawn::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");

// Function BP_POIManager.BP_POIManager_C.UserConstructionScript
// 0x0480 (0x0480 - 0x0000)
struct BP_POIManager_C_UserConstructionScript final
{
public:
	struct FHitResult                             CallFunc_K2_AddLocalOffset_SweepHitResult;         // 0x0000(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0100(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0118(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0130(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0148(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0160(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x01C0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_AddLocalOffset_SweepHitResult_1;       // 0x02A8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsPackagedForDistribution_ReturnValue;    // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_391[0x7];                                      // 0x0391(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_AddLocalOffset_SweepHitResult_2;       // 0x0398(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_POIManager_C_UserConstructionScript) == 0x000010, "Wrong alignment on BP_POIManager_C_UserConstructionScript");
static_assert(sizeof(BP_POIManager_C_UserConstructionScript) == 0x000480, "Wrong size on BP_POIManager_C_UserConstructionScript");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_K2_AddLocalOffset_SweepHitResult) == 0x000000, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_K2_AddLocalOffset_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000E8, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_BreakTransform_Location) == 0x000100, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_BreakTransform_Rotation) == 0x000118, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_BreakTransform_Scale) == 0x000130, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_Add_VectorVector_ReturnValue) == 0x000148, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_MakeTransform_ReturnValue) == 0x000160, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x0001C0, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_K2_AddLocalOffset_SweepHitResult_1) == 0x0002A8, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_K2_AddLocalOffset_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_IsPackagedForDistribution_ReturnValue) == 0x000390, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_IsPackagedForDistribution_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_POIManager_C_UserConstructionScript, CallFunc_K2_AddLocalOffset_SweepHitResult_2) == 0x000398, "Member 'BP_POIManager_C_UserConstructionScript::CallFunc_K2_AddLocalOffset_SweepHitResult_2' has a wrong offset!");

}

