#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ToolRequired_GunLocker2

#include "Basic.hpp"

#include "BP_MASTER_ToolRequiredContainer_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ToolRequired_GunLocker2.BP_ToolRequired_GunLocker2_C
// 0x0000 (0x03E0 - 0x03E0)
class ABP_ToolRequired_GunLocker2_C final : public ABP_MASTER_ToolRequiredContainer_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ToolRequired_GunLocker2_C">();
	}
	static class ABP_ToolRequired_GunLocker2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ToolRequired_GunLocker2_C>();
	}
};
static_assert(alignof(ABP_ToolRequired_GunLocker2_C) == 0x000010, "Wrong alignment on ABP_ToolRequired_GunLocker2_C");
static_assert(sizeof(ABP_ToolRequired_GunLocker2_C) == 0x0003E0, "Wrong size on ABP_ToolRequired_GunLocker2_C");

}

