#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Damage

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Damage.BPI_Damage_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Damage_C final
{
public:
	void Damage_Object(double Damage, class AActor* Damage_Causer, class AController* Event_Instigator);
	void Damage_Shoved(bool Anim, double Force);
	void IsObjectDamageable_(bool* Damageable_);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Damage_C">();
	}
	static class IBPI_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Damage_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_Damage_C) == 0x000001, "Wrong alignment on IBPI_Damage_C");
static_assert(sizeof(IBPI_Damage_C) == 0x000001, "Wrong size on IBPI_Damage_C");

}

