#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Settlements

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Settlements.BPI_Settlements_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Settlements_C final
{
public:
	void SpawnSettlement();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Settlements_C">();
	}
	static class IBPI_Settlements_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Settlements_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_Settlements_C) == 0x000001, "Wrong alignment on IBPI_Settlements_C");
static_assert(sizeof(IBPI_Settlements_C) == 0x000001, "Wrong size on IBPI_Settlements_C");

}

