#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_FishingRod

#include "Basic.hpp"

#include "BPI_FishingRod_classes.hpp"
#include "BPI_FishingRod_parameters.hpp"


namespace SDK
{

// Function BPI_FishingRod.BPI_FishingRod_C.CastRod
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_FishingRod_C::CastRod()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_FishingRod_C", "CastRod");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function BPI_FishingRod.BPI_FishingRod_C.CatchFish
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_FishingRod_C::CatchFish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_FishingRod_C", "CatchFish");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function BPI_FishingRod.BPI_FishingRod_C.StartFishing
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_FishingRod_C::StartFishing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_FishingRod_C", "StartFishing");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function BPI_FishingRod.BPI_FishingRod_C.StopFishing
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Caught_A_Fish_                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_FishingRod_C::StopFishing(bool Caught_A_Fish_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_FishingRod_C", "StopFishing");

	Params::BPI_FishingRod_C_StopFishing Parms{};

	Parms.Caught_A_Fish_ = Caught_A_Fish_;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

