#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_UI

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_UI.BPI_UI_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_UI_C final
{
public:
	void GetFlashlightDurability(double Dur);
	void GetNightVisionDurability(double Dur);
	void GetRespiratorDurability(double Dur);
	void ShowFlashlightDurability(bool Show_);
	void ShowNightVisionDurability(bool Show_);
	void ShowRespiratorDurability(bool Show_);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_UI_C">();
	}
	static class IBPI_UI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_UI_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_UI_C) == 0x000001, "Wrong alignment on IBPI_UI_C");
static_assert(sizeof(IBPI_UI_C) == 0x000001, "Wrong size on IBPI_UI_C");

}

