#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_WorldObjectPower

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_WorldObjectPower.BPI_WorldObjectPower_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_WorldObjectPower_C final
{
public:
	void SetPower_Warning(bool SetWarning);
	void SetPower_TurnedOn(bool TurnOn);
	void CallInteractOnObject();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_WorldObjectPower_C">();
	}
	static class IBPI_WorldObjectPower_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_WorldObjectPower_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_WorldObjectPower_C) == 0x000001, "Wrong alignment on IBPI_WorldObjectPower_C");
static_assert(sizeof(IBPI_WorldObjectPower_C) == 0x000001, "Wrong size on IBPI_WorldObjectPower_C");

}

