#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_MoneySafe

#include "Basic.hpp"

#include "BuildableMaster_Container_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buildable_MoneySafe.Buildable_MoneySafe_C
// 0x0000 (0x0480 - 0x0480)
class ABuildable_MoneySafe_C final : public ABuildableMaster_Container_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buildable_MoneySafe_C">();
	}
	static class ABuildable_MoneySafe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuildable_MoneySafe_C>();
	}
};
static_assert(alignof(ABuildable_MoneySafe_C) == 0x000008, "Wrong alignment on ABuildable_MoneySafe_C");
static_assert(sizeof(ABuildable_MoneySafe_C) == 0x000480, "Wrong size on ABuildable_MoneySafe_C");

}

