#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PhotoModeDataInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PhotoModeDataInterface.PhotoModeDataInterface_C
// 0x0000 (0x0000 - 0x0000)
class IPhotoModeDataInterface_C final
{
public:
	void SendPhotoData(const struct FPhotosData& PhotoData);
	void TabToOpen(int32 TabIndex, class UCommonButtonTab_C* CommonButtonPressed);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PhotoModeDataInterface_C">();
	}
	static class IPhotoModeDataInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IPhotoModeDataInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IPhotoModeDataInterface_C) == 0x000001, "Wrong alignment on IPhotoModeDataInterface_C");
static_assert(sizeof(IPhotoModeDataInterface_C) == 0x000001, "Wrong size on IPhotoModeDataInterface_C");

}

