#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PicklockContainer_Safe

#include "Basic.hpp"

#include "BP_MASTER_PicklockContainer_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PicklockContainer_Safe.PicklockContainer_Safe_C
// 0x0000 (0x03D0 - 0x03D0)
class APicklockContainer_Safe_C final : public ABP_MASTER_PicklockContainer_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PicklockContainer_Safe_C">();
	}
	static class APicklockContainer_Safe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APicklockContainer_Safe_C>();
	}
};
static_assert(alignof(APicklockContainer_Safe_C) == 0x000010, "Wrong alignment on APicklockContainer_Safe_C");
static_assert(sizeof(APicklockContainer_Safe_C) == 0x0003D0, "Wrong size on APicklockContainer_Safe_C");

}

