#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Temperature_Volume_Interface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Temperature_Volume_Interface.Temperature_Volume_Interface_C
// 0x0000 (0x0000 - 0x0000)
class ITemperature_Volume_Interface_C final
{
public:
	void Query_Temperature_Volume(const struct FVector& Sample_Location, double* Offset, double* Interior_Temp, double* Interior_Alpha);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Temperature_Volume_Interface_C">();
	}
	static class ITemperature_Volume_Interface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ITemperature_Volume_Interface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(ITemperature_Volume_Interface_C) == 0x000001, "Wrong alignment on ITemperature_Volume_Interface_C");
static_assert(sizeof(ITemperature_Volume_Interface_C) == 0x000001, "Wrong size on ITemperature_Volume_Interface_C");

}

