#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleVendorButton

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "S_UpdateCount_structs.hpp"


namespace SDK::Params
{

// Function VehicleVendorButton.VehicleVendorButton_C.GetToolTipWidget
// 0x0008 (0x0008 - 0x0000)
struct VehicleVendorButton_C_GetToolTipWidget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VehicleVendorButton_C_GetToolTipWidget) == 0x000008, "Wrong alignment on VehicleVendorButton_C_GetToolTipWidget");
static_assert(sizeof(VehicleVendorButton_C_GetToolTipWidget) == 0x000008, "Wrong size on VehicleVendorButton_C_GetToolTipWidget");
static_assert(offsetof(VehicleVendorButton_C_GetToolTipWidget, ReturnValue) == 0x000000, "Member 'VehicleVendorButton_C_GetToolTipWidget::ReturnValue' has a wrong offset!");

// Function VehicleVendorButton.VehicleVendorButton_C.GetPrice
// 0x0090 (0x0090 - 0x0000)
struct VehicleVendorButton_C_GetPrice final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0018(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0068(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0078(0x0018)()
};
static_assert(alignof(VehicleVendorButton_C_GetPrice) == 0x000008, "Wrong alignment on VehicleVendorButton_C_GetPrice");
static_assert(sizeof(VehicleVendorButton_C_GetPrice) == 0x000090, "Wrong size on VehicleVendorButton_C_GetPrice");
static_assert(offsetof(VehicleVendorButton_C_GetPrice, ReturnValue) == 0x000000, "Member 'VehicleVendorButton_C_GetPrice::ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_GetPrice, K2Node_MakeStruct_FormatArgumentData) == 0x000018, "Member 'VehicleVendorButton_C_GetPrice::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_GetPrice, K2Node_MakeArray_Array) == 0x000068, "Member 'VehicleVendorButton_C_GetPrice::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_GetPrice, CallFunc_Format_ReturnValue) == 0x000078, "Member 'VehicleVendorButton_C_GetPrice::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function VehicleVendorButton.VehicleVendorButton_C.ExecuteUbergraph_VehicleVendorButton
// 0x0170 (0x0170 - 0x0000)
struct VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVehicleTooltip_C*                      CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_JigMultiplayer_C*                   CallFunc_GetComponentByClass_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Text_to_Int_Return_Value;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TakeMoney_ReturnValue;                    // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FS_UpdateCount>                 CallFunc_TakeMoney_UpdateMoneyCount;               // 0x0028(0x0010)(ReferenceParm)
	bool                                          CallFunc_CheckIfHasEnoughMoney_ReturnValue;        // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0040(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x0080(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0098(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x00E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0100(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0160(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton) == 0x000010, "Wrong alignment on VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton");
static_assert(sizeof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton) == 0x000170, "Wrong size on VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, EntryPoint) == 0x000000, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::EntryPoint' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_Create_ReturnValue) == 0x000008, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_GetPlayerPawn_ReturnValue) == 0x000010, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_GetComponentByClass_ReturnValue) == 0x000018, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_Text_to_Int_Return_Value) == 0x000020, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_Text_to_Int_Return_Value' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_TakeMoney_ReturnValue) == 0x000024, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_TakeMoney_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_TakeMoney_UpdateMoneyCount) == 0x000028, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_TakeMoney_UpdateMoneyCount' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_CheckIfHasEnoughMoney_ReturnValue) == 0x000038, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_CheckIfHasEnoughMoney_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x000040, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_GetPlayerController_ReturnValue) == 0x000058, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_GetActorForwardVector_ReturnValue) == 0x000060, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_GetPlayerCharacter_ReturnValue) == 0x000078, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_GetPlayerCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_Multiply_VectorVector_ReturnValue) == 0x000080, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000098, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_Add_VectorVector_ReturnValue) == 0x0000B0, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_BreakVector_X) == 0x0000C8, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_BreakVector_Y) == 0x0000D0, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_BreakVector_Z) == 0x0000D8, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_Add_DoubleDouble_ReturnValue) == 0x0000E0, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_MakeVector_ReturnValue) == 0x0000E8, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_MakeTransform_ReturnValue) == 0x000100, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000160, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton, CallFunc_FinishSpawningActor_ReturnValue) == 0x000168, "Member 'VehicleVendorButton_C_ExecuteUbergraph_VehicleVendorButton::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");

}

