#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleFuelComponent

#include "Basic.hpp"

#include "VehicleFuelComponent_classes.hpp"
#include "VehicleFuelComponent_parameters.hpp"


namespace SDK
{

// Function VehicleFuelComponent.VehicleFuelComponent_C.AddFuel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  FuelPercent                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVehicleFuelComponent_C::AddFuel(double FuelPercent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "AddFuel");

	Params::VehicleFuelComponent_C_AddFuel Parms{};

	Parms.FuelPercent = FuelPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.Event_FuelX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVehicleFuelComponent_C::Event_FuelX(float NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "Event_FuelX");

	Params::VehicleFuelComponent_C_Event_FuelX Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.ExecuteUbergraph_VehicleFuelComponent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVehicleFuelComponent_C::ExecuteUbergraph_VehicleFuelComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "ExecuteUbergraph_VehicleFuelComponent");

	Params::VehicleFuelComponent_C_ExecuteUbergraph_VehicleFuelComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.FuelSpend
// (BlueprintCallable, BlueprintEvent)

void UVehicleFuelComponent_C::FuelSpend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "FuelSpend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.LoadComponent
// (BlueprintCallable, BlueprintEvent)

void UVehicleFuelComponent_C::LoadComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "LoadComponent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UVehicleFuelComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.StartFuelSpend
// (BlueprintCallable, BlueprintEvent)

void UVehicleFuelComponent_C::StartFuelSpend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "StartFuelSpend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.StopSpendFuel
// (BlueprintCallable, BlueprintEvent)

void UVehicleFuelComponent_C::StopSpendFuel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "StopSpendFuel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VehicleFuelComponent.VehicleFuelComponent_C.UpdateUIFuel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Fuel                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVehicleFuelComponent_C::UpdateUIFuel(double Fuel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleFuelComponent_C", "UpdateUIFuel");

	Params::VehicleFuelComponent_C_UpdateUIFuel Parms{};

	Parms.Fuel = Fuel;

	UObject::ProcessEvent(Func, &Parms);
}

}

