#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VehicleUI

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function VehicleUI.VehicleUI_C.ExecuteUbergraph_VehicleUI
// 0x00C8 (0x00C8 - 0x0000)
struct VehicleUI_C_ExecuteUbergraph_VehicleUI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_PlayerCharacter_C*                  CallFunc_CastToCharacter_Character;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_Fuel;                           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_Health;                         // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0038(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_75[0x3];                                       // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetForwardSpeedMPH_ReturnValue;           // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Abs_ReturnValue;                          // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_DoubleToText_ReturnValue;            // 0x0088(0x0018)()
	class FText                                   CallFunc_Append_Text_Return_Value;                 // 0x00A0(0x0018)()
	float                                         CallFunc_SetPercent_InPercent_ImplicitCast;        // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetPercent_InPercent_ImplicitCast_1;      // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Abs_A_ImplicitCast;                       // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VehicleUI_C_ExecuteUbergraph_VehicleUI) == 0x000008, "Wrong alignment on VehicleUI_C_ExecuteUbergraph_VehicleUI");
static_assert(sizeof(VehicleUI_C_ExecuteUbergraph_VehicleUI) == 0x0000C8, "Wrong size on VehicleUI_C_ExecuteUbergraph_VehicleUI");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, EntryPoint) == 0x000000, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::EntryPoint' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_CastToCharacter_Character) == 0x000010, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_CastToCharacter_Character' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, K2Node_CustomEvent_Fuel) == 0x000018, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::K2Node_CustomEvent_Fuel' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, K2Node_CustomEvent_Health) == 0x000020, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::K2Node_CustomEvent_Health' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000028, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x000030, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, K2Node_Event_MyGeometry) == 0x000038, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, K2Node_Event_InDeltaTime) == 0x000070, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_IsValid_ReturnValue) == 0x000074, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_GetForwardSpeedMPH_ReturnValue) == 0x000078, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_GetForwardSpeedMPH_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_Abs_ReturnValue) == 0x000080, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_Abs_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_Conv_DoubleToText_ReturnValue) == 0x000088, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_Conv_DoubleToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_Append_Text_Return_Value) == 0x0000A0, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_Append_Text_Return_Value' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_SetPercent_InPercent_ImplicitCast) == 0x0000B8, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_SetPercent_InPercent_ImplicitCast' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_SetPercent_InPercent_ImplicitCast_1) == 0x0000BC, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_SetPercent_InPercent_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_ExecuteUbergraph_VehicleUI, CallFunc_Abs_A_ImplicitCast) == 0x0000C0, "Member 'VehicleUI_C_ExecuteUbergraph_VehicleUI::CallFunc_Abs_A_ImplicitCast' has a wrong offset!");

// Function VehicleUI.VehicleUI_C.GetName
// 0x0040 (0x0040 - 0x0000)
struct VehicleUI_C_GetName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_GetName_Name;                             // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0028(0x0018)()
};
static_assert(alignof(VehicleUI_C_GetName) == 0x000008, "Wrong alignment on VehicleUI_C_GetName");
static_assert(sizeof(VehicleUI_C_GetName) == 0x000040, "Wrong size on VehicleUI_C_GetName");
static_assert(offsetof(VehicleUI_C_GetName, ReturnValue) == 0x000000, "Member 'VehicleUI_C_GetName::ReturnValue' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_GetName, CallFunc_GetName_Name) == 0x000018, "Member 'VehicleUI_C_GetName::CallFunc_GetName_Name' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_GetName, CallFunc_Conv_StringToText_ReturnValue) == 0x000028, "Member 'VehicleUI_C_GetName::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

// Function VehicleUI.VehicleUI_C.Tick
// 0x003C (0x003C - 0x0000)
struct VehicleUI_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VehicleUI_C_Tick) == 0x000004, "Wrong alignment on VehicleUI_C_Tick");
static_assert(sizeof(VehicleUI_C_Tick) == 0x00003C, "Wrong size on VehicleUI_C_Tick");
static_assert(offsetof(VehicleUI_C_Tick, MyGeometry) == 0x000000, "Member 'VehicleUI_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(VehicleUI_C_Tick, InDeltaTime) == 0x000038, "Member 'VehicleUI_C_Tick::InDeltaTime' has a wrong offset!");

// Function VehicleUI.VehicleUI_C.UpdateFuel
// 0x0008 (0x0008 - 0x0000)
struct VehicleUI_C_UpdateFuel final
{
public:
	double                                        Fuel;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VehicleUI_C_UpdateFuel) == 0x000008, "Wrong alignment on VehicleUI_C_UpdateFuel");
static_assert(sizeof(VehicleUI_C_UpdateFuel) == 0x000008, "Wrong size on VehicleUI_C_UpdateFuel");
static_assert(offsetof(VehicleUI_C_UpdateFuel, Fuel) == 0x000000, "Member 'VehicleUI_C_UpdateFuel::Fuel' has a wrong offset!");

// Function VehicleUI.VehicleUI_C.UpdateHealth
// 0x0008 (0x0008 - 0x0000)
struct VehicleUI_C_UpdateHealth final
{
public:
	double                                        Health;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VehicleUI_C_UpdateHealth) == 0x000008, "Wrong alignment on VehicleUI_C_UpdateHealth");
static_assert(sizeof(VehicleUI_C_UpdateHealth) == 0x000008, "Wrong size on VehicleUI_C_UpdateHealth");
static_assert(offsetof(VehicleUI_C_UpdateHealth, Health) == 0x000000, "Member 'VehicleUI_C_UpdateHealth::Health' has a wrong offset!");

}

