#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zombie_FindPlayerLocation

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Zombie_FindPlayerLocation.Zombie_FindPlayerLocation_C
// 0x0050 (0x00F8 - 0x00A8)
class UZombie_FindPlayerLocation_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 Location;                                          // 0x00B0(0x0028)(Edit, BlueprintVisible)
	class AActor*                                 Actor;                                             // 0x00D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ActorLocation;                                     // 0x00E0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Zombie_FindPlayerLocation(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Zombie_FindPlayerLocation_C">();
	}
	static class UZombie_FindPlayerLocation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UZombie_FindPlayerLocation_C>();
	}
};
static_assert(alignof(UZombie_FindPlayerLocation_C) == 0x000008, "Wrong alignment on UZombie_FindPlayerLocation_C");
static_assert(sizeof(UZombie_FindPlayerLocation_C) == 0x0000F8, "Wrong size on UZombie_FindPlayerLocation_C");
static_assert(offsetof(UZombie_FindPlayerLocation_C, UberGraphFrame) == 0x0000A8, "Member 'UZombie_FindPlayerLocation_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UZombie_FindPlayerLocation_C, Location) == 0x0000B0, "Member 'UZombie_FindPlayerLocation_C::Location' has a wrong offset!");
static_assert(offsetof(UZombie_FindPlayerLocation_C, Actor) == 0x0000D8, "Member 'UZombie_FindPlayerLocation_C::Actor' has a wrong offset!");
static_assert(offsetof(UZombie_FindPlayerLocation_C, ActorLocation) == 0x0000E0, "Member 'UZombie_FindPlayerLocation_C::ActorLocation' has a wrong offset!");

}

